version: '3.7'

services: 
  invoices:
    build: 
      context: .
    ports: 
      - "8000:8000"
    volumes: 
      - ./invoices:/invoices
    secrets:
      - my_external_secret
    command: sh -c "python ../manage.py runserver 0.0.0.0:8000"
    environment: 
      - DEBUG=1
secrets:                        # top level secrets block
  my_external_secret:
    external: true
    
  
