# Generated by Django 4.2.7 on 2023-11-15 20:41

from django.db import migrations, models
import invoices.actions.helpers
import invoices.models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial_after_major_november_cleanup'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicingdetails',
            name='xero_tenant_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bedsoreevaluation',
            name='image',
            field=models.ImageField(upload_to=invoices.actions.helpers.update_bedsore_pictures_filenames, validators=[invoices.models.validate_image]),
        ),
    ]
