# Generated by Django 4.2.7 on 2023-11-15 19:05

from django.db import migrations, models
import invoices.actions.helpers
import invoices.models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_initial_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simplifiedtimesheetdetail',
            name='coordinates_at_end_date',
        ),
        migrations.RemoveField(
            model_name='simplifiedtimesheetdetail',
            name='coordinates_at_start_date',
        ),
        migrations.AlterField(
            model_name='bedsoreevaluation',
            name='image',
            field=models.ImageField(upload_to=invoices.actions.helpers.update_bedsore_pictures_filenames, validators=[invoices.models.validate_image]),
        ),
    ]
