# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_auto_20160224_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name=b'Timesheet start date')),
                ('end_date', models.DateField(verbose_name=b'Timesheet end date')),
                ('submitted_date', models.DateTimeField(verbose_name=b'submitted date')),
                ('other_details', models.TextField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimesheetDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name=b'start date')),
                ('end_date', models.DateTimeField(verbose_name=b'end date')),
                ('task_description', models.CharField(max_length=30)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.Patient')),
                ('timesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.Timesheet')),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.AlterField(
            model_name='employee',
            name='end_contract',
            field=models.DateField(blank=True, null=True, verbose_name=b'end date'),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.Employee'),
        ),
    ]
