# Generated by Django 4.2.7 on 2023-11-16 12:07

from django.db import migrations, models
import invoices.actions.helpers
import invoices.models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_cleanup_xero'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='xero_invoice_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bedsoreevaluation',
            name='image',
            field=models.ImageField(upload_to=invoices.actions.helpers.update_bedsore_pictures_filenames, validators=[invoices.models.validate_image]),
        ),
    ]
