# Generated by Django 4.2.7 on 2023-11-24 14:55

from django.db import migrations, models
import invoices.actions.helpers
import invoices.models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_add_xero_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('invoices.employee',),
        ),
        migrations.AlterModelOptions(
            name='eventweeklist',
            options={'verbose_name': "Nouveau Planning (Ne modifiez pas les événements à partir d'ici)", 'verbose_name_plural': "Nouveaux Plannings (Ne modifiez pas les événements à partir d'ici)"},
        ),
        migrations.AddField(
            model_name='jobposition',
            name='job_type',
            field=models.CharField(choices=[('soignant', 'Soignant'), ('administratif', 'Administratif'), ('logistique', 'Logistique')], default='soignant', max_length=20, verbose_name='Type de poste'),
        ),
        migrations.AlterField(
            model_name='bedsoreevaluation',
            name='image',
            field=models.ImageField(upload_to=invoices.actions.helpers.update_bedsore_pictures_filenames, validators=[invoices.models.validate_image]),
        ),
    ]
