# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_auto_20160308_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimesheetTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='timesheetdetail',
            name='task_description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.TimesheetTask'),
        ),
    ]
