# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_auto_20160308_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timesheet',
            old_name='timesheet_submitted',
            new_name='timesheet_validated',
        ),
        migrations.RemoveField(
            model_name='timesheetdetail',
            name='task_description',
        ),
        migrations.AddField(
            model_name='timesheetdetail',
            name='task_description',
            field=models.ManyToManyField(help_text=b'Entrez une ou plusieurs taches.', to='invoices.TimesheetTask'),
        ),
    ]
