# Generated by Django 4.2.8 on 2023-12-08 22:01

from django.db import migrations, models
import django.db.models.deletion
import invoices.actions.helpers
import invoices.models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_create_return_file_for_declaration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedsoreevaluation',
            name='image',
            field=models.ImageField(upload_to=invoices.actions.helpers.update_bedsore_pictures_filenames, validators=[invoices.models.validate_image]),
        ),
        migrations.CreateModel(
            name='DistanceMatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_in_km', models.PositiveSmallIntegerField()),
                ('duration_in_mn', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_destination_distance_matrix', to='invoices.patient')),
                ('patient_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_origin_distance_matrix', to='invoices.patient')),
            ],
            options={
                'verbose_name': 'Distance Matrix',
                'verbose_name_plural': 'Distances Matrix',
                'ordering': ['patient_origin', 'patient_destination'],
                'unique_together': {('patient_origin', 'patient_destination')},
            },
        ),
    ]
