# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-03 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_auto_20160308_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='carecode',
            name='reimbursed',
            field=models.BooleanField(default=True, verbose_name=b'Prise en charge par CNS'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='timesheet_validated',
            field=models.BooleanField(default=False, verbose_name=b'Valide'),
        ),
    ]
