# Generated by Django 4.2.8 on 2023-12-18 19:35

from django.db import migrations, models
import django_countries.fields
import invoices.actions.helpers
import invoices.models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_generate_distance_matrix_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubContractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(max_length=255)),
                ('zipcode', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=30)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('phone_number', models.CharField(max_length=30)),
                ('fax_number', models.CharField(blank=True, max_length=30, null=True)),
                ('email_address', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('provider_code', models.CharField(blank=True, max_length=30, null=True, verbose_name='Code Prestataire')),
                ('billing_retrocession', models.DecimalField(decimal_places=2, default=15, max_digits=10, verbose_name='Rétrocession facturation')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
            ],
        ),
        migrations.AlterField(
            model_name='bedsoreevaluation',
            name='image',
            field=models.ImageField(upload_to=invoices.actions.helpers.update_bedsore_pictures_filenames, validators=[invoices.models.validate_image]),
        ),
        migrations.AddField(
            model_name='patient',
            name='subcontractors',
            field=models.ManyToManyField(blank=True, to='invoices.subcontractor'),
        ),
    ]
