# Generated by Django 4.2.8 on 2023-12-18 20:22

from django.db import migrations, models
import django.db.models.deletion
import invoices.actions.helpers
import invoices.models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_subcontractor_ftr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedsoreevaluation',
            name='image',
            field=models.ImageField(upload_to=invoices.actions.helpers.update_bedsore_pictures_filenames, validators=[invoices.models.validate_image]),
        ),
        migrations.CreateModel(
            name='SubContractorAdminFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='subcontractor_files/')),
                ('description', models.TextField()),
                ('subcontractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.subcontractor')),
            ],
        ),
    ]
