# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-03 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_auto_20161003_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='invoice_send_date',
            field=models.DateField(blank=True, null=True, verbose_name=b'Date envoi facture'),
        ),
    ]
