# Generated by Django 4.2.8 on 2023-12-18 20:29

from django.db import migrations, models
import django.db.models.deletion
import invoices.actions.helpers
import invoices.models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0009_subcontractor_ftr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='subcontractors',
        ),
        migrations.AlterField(
            model_name='bedsoreevaluation',
            name='image',
            field=models.ImageField(upload_to=invoices.actions.helpers.update_bedsore_pictures_filenames, validators=[invoices.models.validate_image]),
        ),
        migrations.CreateModel(
            name='PatientSubContractorRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('contractor', 'We are Sub-Contractor'), ('main_company', 'Wee are Main Company')], max_length=50)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.patient')),
                ('subcontractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.subcontractor')),
            ],
        ),
    ]
