# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0009_invoiceitem_invoice_send_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='email_address',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
    ]
