# Generated by Django 4.2.8 on 2023-12-21 15:39

from django.db import migrations, models
import invoices.actions.helpers
import invoices.models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_subcontractor_ftr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedsoreevaluation',
            name='image',
            field=models.ImageField(upload_to=invoices.actions.helpers.update_bedsore_pictures_filenames, validators=[invoices.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='patientsubcontractorrelationship',
            name='relationship_type',
            field=models.CharField(choices=[('contractor', 'We are Sub-Contractor'), ('main_company', 'We are Main Company')], max_length=50),
        ),
    ]
