# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-21 11:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_patient_email_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Physician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_sn', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('address', models.TextField(max_length=30)),
                ('zipcode', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=30)),
                ('email_address', models.EmailField(blank=True, default=None, max_length=254, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='physician',
            field=models.ForeignKey(blank=True, help_text=b'Please chose the physican who is givng the medical prescription', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='physician', to='invoices.Physician'),
        ),
    ]
