# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-30 12:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_patient_email_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='carecode',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carecode',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
