# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-21 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0011_add_physician'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privateinvoiceitem',
            name='prestations',
        ),
        migrations.RemoveField(
            model_name='privateinvoiceitem',
            name='private_patient',
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='PrivateInvoiceItem',
        ),
    ]
