# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-21 11:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0013_remove_prestation_rel_to_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='prestations',
        ),
        migrations.AddField(
            model_name='prestation',
            name='invoice_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='invoices.InvoiceItem'),
            preserve_default=False,
        ),
    ]
