# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-21 12:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0014_remove_prestation_rel_to_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='private_patient',
            new_name='is_private',
        ),
    ]
