# Generated by Django 4.2.8 on 2024-01-24 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import invoices.actions.helpers
import invoices.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoices', '0017_enlarge_custom_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcontractor',
            options={'ordering': ['-id'], 'verbose_name': 'Sous-traitant', 'verbose_name_plural': 'Sous-traitants'},
        ),
        migrations.AddField(
            model_name='subcontractor',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subcontractor_created_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcontractor',
            name='end_collaboration_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Date fin de collaboration'),
        ),
        migrations.AddField(
            model_name='subcontractor',
            name='start_collaboration_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Date début de collaboration'),
        ),
        migrations.AlterField(
            model_name='bedsoreevaluation',
            name='image',
            field=models.ImageField(upload_to=invoices.actions.helpers.update_bedsore_pictures_filenames, validators=[invoices.models.validate_image]),
        ),
    ]
