# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-23 17:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0018_prestation_to_employee_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='is_private',
            field=models.BooleanField(default=False, help_text=b'Seuls les patients qui ne disposent pas de la prise en charge CNS seront recherches dans le champ Patient (prive)', verbose_name=b'Facture pour patient non pris en charge par CNS'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='patient',
            field=models.ForeignKey(help_text='choisir parmi les patients en entrant quelques lettres de son nom ou prenom', on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='invoices.Patient'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='patient_invoice_date',
            field=models.DateField(blank=True, null=True, verbose_name=b'Date envoi au patient'),
        ),
    ]
