# Generated by Django 4.2.8 on 2024-01-24 10:55

from django.db import migrations, models
import invoices.actions.helpers
import invoices.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0019_add_owner_of_subcontractor'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcontractor',
            name='mobile_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Numéro de tél. mobile'),
        ),
        migrations.AlterField(
            model_name='bedsoreevaluation',
            name='image',
            field=models.ImageField(upload_to=invoices.actions.helpers.update_bedsore_pictures_filenames, validators=[invoices.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='subcontractor',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Numéro de tél.'),
        ),
    ]
