# Generated by Django 4.2.8 on 2024-01-25 14:48

from django.db import migrations, models
import django.utils.timezone
import invoices.actions.helpers
import invoices.models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0020_add_owner_of_subcontractor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='physician',
            options={'ordering': ['-id'], 'verbose_name': 'Médecin', 'verbose_name_plural': 'Médecins'},
        ),
        migrations.AddField(
            model_name='physician',
            name='cns_speciality_code',
            field=models.CharField(blank=True, default=None, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='physician',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date création'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='physician',
            name='is_foreign_physician',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='physician',
            name='practice_end_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='physician',
            name='practice_start_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='physician',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour'),
        ),
        migrations.AlterField(
            model_name='bedsoreevaluation',
            name='image',
            field=models.ImageField(upload_to=invoices.actions.helpers.update_bedsore_pictures_filenames, validators=[invoices.models.validate_image]),
        ),
    ]
