# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-24 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0021_physician_rename_code_sn_to_provider_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='country',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
