# Generated by Django 4.2.8 on 2024-01-30 15:16

from django.db import migrations, models
import invoices.actions.helpers
import invoices.models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0022_physician_improve'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physician',
            name='full_address_from_cns',
        ),
        migrations.AddField(
            model_name='subcontractor',
            name='contractor_profession',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Profession'),
        ),
        migrations.AlterField(
            model_name='bedsoreevaluation',
            name='image',
            field=models.ImageField(upload_to=invoices.actions.helpers.update_bedsore_pictures_filenames, validators=[invoices.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='physician',
            name='is_foreign_physician',
            field=models.BooleanField(default=False, verbose_name='Médecin étranger'),
        ),
    ]
