# Generated by Django 4.2.8 on 2024-02-02 10:58

from django.db import migrations, models
import django.db.models.deletion
import invoices.actions.helpers
import invoices.models


class Migration(migrations.Migration):

    dependencies = [
        ('dependence', '0008_generic_event_links'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('invoices', '0023_add_subcontractor_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sub_contractor',
            field=models.ForeignKey(blank=True, help_text='Please select a sub contractor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='event_link_to_sub_contractor', to='invoices.subcontractor'),
        ),
        migrations.AlterField(
            model_name='bedsoreevaluation',
            name='image',
            field=models.ImageField(upload_to=invoices.actions.helpers.update_bedsore_pictures_filenames, validators=[invoices.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type_enum',
            field=models.CharField(choices=[('BIRTHDAY', 'Birthday'), ('CARE', 'Soin'), ('ASS_DEP', 'Soin Assurance dépendance'), ('GENERIC', 'Général pour Patient (non soin)'), ('GNRC_EMPL', 'Général pour Employé'), ('SUB_CARE', 'Soin(s) en sous-traitance'), ('AAI', 'AAI')], default='CARE', max_length=10, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='simplifiedtimesheet',
            name='time_sheet_month',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], default=2),
        ),
        migrations.CreateModel(
            name='GenericTaskDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Descriptive Name')),
                ('is_done', models.BooleanField(default=False, verbose_name='Is Done')),
                ('not_done_reason', models.TextField(blank=True, null=True, verbose_name='Reason if not done')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.event')),
            ],
            options={
                'verbose_name': 'Generic Task Description',
                'verbose_name_plural': 'Generic Task Descriptions',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='EventLinkToMedicalCareSummaryPerPatientDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_done', models.BooleanField(default=False, verbose_name='Is Done')),
                ('not_done_reason', models.TextField(blank=True, null=True, verbose_name='Reason if not done')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.event')),
                ('medical_care_summary_per_patient_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dependence.medicalcaresummaryperpatientdetail')),
            ],
            options={
                'verbose_name': 'Event -> Link to Medical Care Summary Per Patient Detail',
                'verbose_name_plural': 'Event -> Link to Medical Care Summary Per Patient Details',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='EventLinkToCareCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_done', models.BooleanField(default=False, verbose_name='Is Done')),
                ('not_done_reason', models.TextField(blank=True, null=True, verbose_name='Reason if not done')),
                ('care_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.carecode')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.event')),
            ],
            options={
                'verbose_name': 'Event -> Link to Care Code',
                'verbose_name_plural': 'Event -> Link to Care Codes',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='EventGenericLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('is_done', models.BooleanField(default=False, verbose_name='Is Done')),
                ('not_done_reason', models.TextField(blank=True, null=True, verbose_name='Reason if not done')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.event')),
            ],
            options={
                'unique_together': {('event', 'content_type', 'object_id')},
            },
        ),
    ]
