# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-28 12:01
from __future__ import unicode_literals

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0023_patient_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physician',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
