# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-28 23:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0024_physician_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareCodeValidityDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name=b'date debut validite')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name=b'date fin validite')),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=5, verbose_name=b'montant brut')),
            ],
        ),
        migrations.RemoveField(
            model_name='carecode',
            name='gross_amount',
        ),
        migrations.AddField(
            model_name='carecodevaliditydates',
            name='validity_dates',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validitiy_dates', to='invoices.CareCode'),
        ),
    ]
