# Generated by Django 4.2.8 on 2024-02-02 17:40

from django.db import migrations, models
import invoices.actions.helpers
import invoices.models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0024_generic_event_links'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventlinktomedicalcaresummaryperpatientdetail',
            options={'ordering': ['-id'], 'verbose_name': 'AEV', 'verbose_name_plural': 'AEVs'},
        ),
        migrations.AddField(
            model_name='eventlinktomedicalcaresummaryperpatientdetail',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='bedsoreevaluation',
            name='image',
            field=models.ImageField(upload_to=invoices.actions.helpers.update_bedsore_pictures_filenames, validators=[invoices.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type_enum',
            field=models.CharField(choices=[('BIRTHDAY', 'Birthday'), ('CARE', 'Soin'), ('ASS_DEP', 'Soin Assurance dépendance'), ('GENERIC', 'Général pour Patient (non soin)'), ('GNRC_EMPL', 'Général pour Employé'), ('SUB_CARE', 'Soin(s) en sous-traitance')], default='CARE', max_length=10, verbose_name='Type'),
        ),
    ]
