# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-28 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0024_physician_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='invoice_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='invoice_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='participation_statutaire',
            field=models.BooleanField(default=False),
        ),
    ]
