# Generated by Django 4.2.8 on 2024-02-04 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import invoices.actions.helpers
import invoices.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoices', '0025_add_qty_to_aev_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedsoreevaluation',
            name='image',
            field=models.ImageField(upload_to=invoices.actions.helpers.update_bedsore_pictures_filenames, validators=[invoices.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='event',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Waiting for validation'), (2, 'Valid'), (3, 'Done'), (4, 'Ignored'), (5, 'Not Done'), (6, 'Cancelled')], default=2, verbose_name='State'),
        ),
        migrations.CreateModel(
            name='ClientPatientRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.patient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
