# Generated by Django 4.2.10 on 2024-02-27 09:37

from django.db import migrations, models
import invoices.actions.helpers
import invoices.employee
import invoices.models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0027_add_last_updated_on_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='minified_avatar',
            field=models.ImageField(blank=True, help_text='You can attach the minified version of the avatar', null=True, upload_to=invoices.employee.avatar_storage_location, validators=[invoices.employee.validate_avatar]),
        ),
        migrations.AlterField(
            model_name='bedsoreevaluation',
            name='image',
            field=models.ImageField(upload_to=invoices.actions.helpers.update_bedsore_pictures_filenames, validators=[invoices.models.validate_image]),
        ),
    ]
