# Generated by Django 4.2.10 on 2024-03-04 10:42

from django.db import migrations, models
import invoices.actions.helpers
import invoices.employee
import invoices.models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0028_minified_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedsoreevaluation',
            name='image',
            field=models.ImageField(upload_to=invoices.actions.helpers.update_bedsore_pictures_filenames, validators=[invoices.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='minified_avatar',
            field=models.ImageField(blank=True, help_text='You can attach the minified version of the avatar', null=True, upload_to=invoices.employee.minified_avatar_storage_location, validators=[invoices.employee.validate_avatar]),
        ),
        migrations.AlterField(
            model_name='simplifiedtimesheet',
            name='time_sheet_month',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], default=3),
        ),
    ]
