# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-30 13:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0028_rename_carecodevaliditydates_to_validityddates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carecode',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='carecode',
            name='start_date',
        ),
    ]
