# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-30 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0029_remove_carecode_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validitydate',
            name='validity_dates',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validity_dates', to='invoices.CareCode'),
        ),
    ]
