# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-30 13:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0030_validity_dates_change_related_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='validitydate',
            old_name='validity_dates',
            new_name='care_code',
        ),
    ]
