# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-01 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0032_carecode_unique_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestation',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
