# Generated by Django 4.2.11 on 2024-03-14 14:59

from django.db import migrations, models
import invoices.actions.helpers
import invoices.models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0033_base64_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventweeklist',
            options={'verbose_name': 'Nouveau Planning *', 'verbose_name_plural': 'Nouveaux Plannings *'},
        ),
        migrations.AlterField(
            model_name='bedsoreevaluation',
            name='image',
            field=models.ImageField(upload_to=invoices.actions.helpers.update_bedsore_pictures_filenames, validators=[invoices.models.validate_image]),
        ),
    ]
