# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-01 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0033_prestation_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='carecode',
            name='exclusive_care_codes',
            field=models.ManyToManyField(blank=True, related_name='_carecode_exclusive_care_codes_+', to='invoices.CareCode'),
        ),
    ]
