# Generated by Django 4.2.11 on 2024-03-19 10:35

from django.db import migrations, models
import invoices.actions.helpers
import invoices.models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0036_enhance_invoicing_dependance_invoices'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewCarList',
            fields=[
            ],
            options={
                'verbose_name': 'Véhicule *',
                'verbose_name_plural': 'Véhicules *',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('invoices.car',),
        ),
        migrations.AddField(
            model_name='car',
            name='is_connected_to_bluelink',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bedsoreevaluation',
            name='image',
            field=models.ImageField(upload_to=invoices.actions.helpers.update_bedsore_pictures_filenames, validators=[invoices.models.validate_image]),
        ),
    ]
