# Generated by Django 4.2.11 on 2024-03-21 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import invoices.actions.helpers
import invoices.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoices', '0037_blue_link_flad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedsoreevaluation',
            name='image',
            field=models.ImageField(upload_to=invoices.actions.helpers.update_bedsore_pictures_filenames, validators=[invoices.models.validate_image]),
        ),
        migrations.CreateModel(
            name='CarBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField()),
                ('booking_start_date', models.DateTimeField()),
                ('booking_end_date', models.DateTimeField()),
                ('car_history_during_booking', models.TextField(blank=True, null=True)),
                ('car_link', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.car')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-booking_date'],
            },
        ),
    ]
