# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-05 18:29
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import invoices.models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0037_medical_prescription_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalprescription',
            name='file',
            field=models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(location=b'/home/projects/inurdjango/invoices/../media'), upload_to=invoices.models.update_medical_prescription_filename),
        ),
    ]
