# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-06 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0038_medical_prescription_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestation',
            name='at_home_paired',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paired_at_home', to='invoices.Prestation'),
        ),
    ]
