# Generated by Django 4.2.11 on 2024-03-25 15:31

from django.db import migrations, models
import invoices.actions.helpers
import invoices.models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0039_cleanup_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbooking',
            name='car_unlocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bedsoreevaluation',
            name='image',
            field=models.ImageField(upload_to=invoices.actions.helpers.update_bedsore_pictures_filenames, validators=[invoices.models.validate_image]),
        ),
    ]
