# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-08 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import gdstorage.storage
import invoices.models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0039_prestation_at_home_paired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalprescription',
            name='file',
            field=models.ImageField(blank=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to=invoices.models.update_medical_prescription_filename),
        ),
    ]
