# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-13 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0041_medicalprescription_date_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='medical_prescription_date',
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='medical_prescription',
            field=models.ForeignKey(blank=True, help_text=b'Please chose the physican who is givng the medical prescription', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='invoices.MedicalPrescription'),
        ),
    ]
