# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-13 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0042_medical_prescription_to_invoice_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='physician',
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='medical_prescription',
            field=models.ForeignKey(blank=True, help_text=b'Please chose a Medical Prescription', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='invoices.MedicalPrescription'),
        ),
    ]
