# Generated by Django 4.2.11 on 2024-04-17 13:16

from django.db import migrations, models
import django.db.models.deletion
import invoices.actions.helpers
import invoices.models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0043_update_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='subcontractor',
            field=models.ForeignKey(blank=True, help_text='Please choose a Subcontractor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcontractor_invoice_items', to='invoices.subcontractor'),
        ),
        migrations.AlterField(
            model_name='bedsoreevaluation',
            name='image',
            field=models.ImageField(upload_to=invoices.actions.helpers.update_bedsore_pictures_filenames, validators=[invoices.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='event',
            name='google_chat_message_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
