# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-13 19:12
from __future__ import unicode_literals

from django.db import migrations, models
import invoices.models
import invoices.storages


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0043_invoice_item_remove_rel_to_physician'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalprescription',
            name='file',
            field=models.ImageField(blank=True, storage=invoices.storages.CustomizedGoogleDriveStorage(), upload_to=invoices.models.update_medical_prescription_filename),
        ),
    ]
