# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-14 16:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0045_employee_add_has_gdrive_access'),
        ('invoices', '0045_add_hospitalizations_dd_for_patient'),
    ]

    operations = [
    ]
