# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-14 22:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0046_merge_20171214_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalprescription',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name=b'Date fin des soins'),
        ),
        migrations.AddField(
            model_name='medicalprescription',
            name='patient',
            field=models.ForeignKey(default=None, help_text=b'Please chose the Patient who is receiving the medical prescription', on_delete=django.db.models.deletion.CASCADE, related_name='medical_prescription_patient', to='invoices.Patient'),
        ),
    ]
