# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-14 17:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0046_merge_20171214_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospitalization',
            old_name='hospitalizations_periods',
            new_name='patient',
        ),
    ]
