# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-14 17:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0047_hospitalization_rename_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalization',
            name='patient',
            field=models.ForeignKey(help_text=b'Please enter hospitalization dates of the patient', on_delete=django.db.models.deletion.CASCADE, related_name='hospitalizations', to='invoices.Patient'),
        ),
    ]
