# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-18 14:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0048_hospitalization_rename_reverse_rel'),
        ('invoices', '0047_add_enddate_patient_on_prescriptions'),
    ]

    operations = [
    ]
