# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-19 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0050_make_ordonnance_date_mandatory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='medical_prescription',
            field=models.ForeignKey(blank=True, help_text=b'Please chose a Medical Prescription', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='invoices.MedicalPrescription'),
        ),
    ]
