# Generated by Django 4.2.11 on 2024-05-06 13:10

from django.db import migrations, models
import invoices.actions.helpers
import invoices.models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0051_aai_result_larger'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitembatch',
            name='generated_12_percent_invoice_files',
            field=models.FileField(blank=True, null=True, upload_to=invoices.actions.helpers.invoice_itembatch_medical_prescription_filename, verbose_name='Facture 12% PDF'),
        ),
        migrations.AlterField(
            model_name='bedsoreevaluation',
            name='image',
            field=models.ImageField(upload_to=invoices.actions.helpers.update_bedsore_pictures_filenames, validators=[invoices.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='simplifiedtimesheet',
            name='time_sheet_month',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], default=5),
        ),
    ]
