# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-19 22:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0051_invoiceitem_to_medicalprescription_on_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestation',
            name='at_home_paired',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paired_at_home', to='invoices.Prestation'),
        ),
    ]
