# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-28 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0053_employee_gcalendar_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.TextField(max_length=255),
        ),
    ]
