# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-28 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0054_patient_address_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceItemBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name=b'Invoice batch start date')),
                ('end_date', models.DateField(verbose_name=b'Invoice batch start date')),
            ],
        ),
    ]
