# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-28 18:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0055_invoice_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='invoices.InvoiceItemBatch'),
        ),
    ]
