# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-28 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0056_invoiceitem_to_invoice_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitembatch',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitembatch',
            name='send_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
