# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-28 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0057_invoice_batch_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='invoices.InvoiceItemBatch'),
        ),
    ]
