# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-29 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0060_invoiceitembatch_file_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='has_gdrive_access',
            field=models.BooleanField(default=False, verbose_name=b'Allow access to Google Drive files'),
        ),
    ]
