# Generated by Django 4.2.15 on 2024-08-20 15:15

from django.db import migrations, models
import django.utils.timezone
import invoices.actions.helpers
import invoices.models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0061_employee_training_files'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='training',
            options={'verbose_name': 'Formation', 'verbose_name_plural': 'Formations'},
        ),
        migrations.AddField(
            model_name='training',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='training',
            name='training_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Coût de la formation'),
        ),
        migrations.AddField(
            model_name='training',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bedsoreevaluation',
            name='image',
            field=models.ImageField(upload_to=invoices.actions.helpers.update_bedsore_pictures_filenames, validators=[invoices.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='holidayrequest',
            name='reason',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Congés'), (2, 'Maladie'), (3, 'Formation'), (4, 'Desiderata'), (5, 'Exceptionnel')]),
        ),
        migrations.AlterField(
            model_name='training',
            name='training_location',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Lieu de la formation'),
        ),
    ]
