# Generated by Django 2.2.1 on 2019-05-23 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0062_remove_enddate_tsheet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carecode',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='carecode',
            name='description',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='carecode',
            name='reimbursed',
            field=models.BooleanField(default=True, verbose_name='Prise en charge par CNS'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='end_contract',
            field=models.DateField(blank=True, null=True, verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='has_gcalendar_access',
            field=models.BooleanField(default=False, verbose_name="Allow access to Prestations' calendar"),
        ),
        migrations.AlterField(
            model_name='employee',
            name='has_gdrive_access',
            field=models.BooleanField(default=False, verbose_name='Allow access to Google Drive files'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='start_contract',
            field=models.DateField(verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='hospitalization',
            name='patient',
            field=models.ForeignKey(help_text='Please enter hospitalization dates of the patient', on_delete=django.db.models.deletion.CASCADE, related_name='hospitalizations', to='invoices.Patient'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='invoice_date',
            field=models.DateField(verbose_name='Invoice date'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='invoice_send_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date envoi facture'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Seuls les patients qui ne disposent pas de la prise en charge CNS seront recherches dans le champ Patient (prive)', verbose_name='Facture pour patient non pris en charge par CNS'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='medical_prescription',
            field=models.ForeignKey(blank=True, help_text='Please chose a Medical Prescription', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='invoices.MedicalPrescription'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='patient_invoice_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date envoi au patient'),
        ),
        migrations.AlterField(
            model_name='invoiceitembatch',
            name='end_date',
            field=models.DateField(verbose_name='Invoice batch start date'),
        ),
        migrations.AlterField(
            model_name='invoiceitembatch',
            name='start_date',
            field=models.DateField(verbose_name='Invoice batch start date'),
        ),
        migrations.AlterField(
            model_name='medicalprescription',
            name='date',
            field=models.DateField(verbose_name='Date ordonnance'),
        ),
        migrations.AlterField(
            model_name='medicalprescription',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date fin des soins'),
        ),
        migrations.AlterField(
            model_name='medicalprescription',
            name='patient',
            field=models.ForeignKey(default=None, help_text='Please chose the Patient who is receiving the medical prescription', on_delete=django.db.models.deletion.CASCADE, related_name='medical_prescription_patient', to='invoices.Patient'),
        ),
        migrations.AlterField(
            model_name='medicalprescription',
            name='prescriptor',
            field=models.ForeignKey(help_text='Please chose the Physician who is giving the medical prescription', on_delete=django.db.models.deletion.CASCADE, related_name='medical_prescription', to='invoices.Physician'),
        ),
        migrations.AlterField(
            model_name='prestation',
            name='date',
            field=models.DateTimeField(verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='end_date',
            field=models.DateField(verbose_name='Date fin'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='other_details',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Autres details'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='start_date',
            field=models.DateField(verbose_name='Date debut'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='submitted_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi"),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='timesheet_validated',
            field=models.BooleanField(default=False, verbose_name='Valide'),
        ),
        migrations.AlterField(
            model_name='timesheetdetail',
            name='end_date',
            field=models.TimeField(verbose_name='Heure fin'),
        ),
        migrations.AlterField(
            model_name='timesheetdetail',
            name='start_date',
            field=models.DateTimeField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='timesheetdetail',
            name='task_description',
            field=models.ManyToManyField(help_text='Entrez une ou plusieurs taches.', to='invoices.TimesheetTask', verbose_name='Description(s) tache'),
        ),
        migrations.AlterField(
            model_name='validitydate',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='date fin validite'),
        ),
        migrations.AlterField(
            model_name='validitydate',
            name='gross_amount',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='montant brut'),
        ),
        migrations.AlterField(
            model_name='validitydate',
            name='start_date',
            field=models.DateField(verbose_name='date debut validite'),
        ),
    ]
