# Generated by Django 2.2.2 on 2019-06-23 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0065_may2019_import_cns_prices'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimplifiedTimesheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Date debut')),
                ('end_date', models.DateField(verbose_name='Date fin')),
                ('submitted_date', models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi")),
                ('other_details', models.TextField(blank=True, max_length=100, null=True, verbose_name='Autres details')),
                ('timesheet_validated', models.BooleanField(default=False, verbose_name='Valide')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.Employee')),
            ],
        ),
        migrations.AlterModelOptions(
            name='validitydate',
            options={'ordering': ['-id']},
        ),
        migrations.CreateModel(
            name='SimplifiedTimesheetDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='Date')),
                ('end_date', models.TimeField(verbose_name='Heure fin')),
                ('timesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.SimplifiedTimesheet')),
            ],
        ),
        migrations.RenameField(
            model_name='simplifiedtimesheetdetail',
            old_name='timesheet',
            new_name='simplified_timesheet',
        ),
        migrations.RemoveField(
            model_name='simplifiedtimesheet',
            name='other_details',
        ),
        migrations.RemoveField(
            model_name='simplifiedtimesheet',
            name='submitted_date',
        ),
        migrations.AlterField(
            model_name='simplifiedtimesheet',
            name='end_date',
            field=models.DateField(
                help_text='Date de fin de votre timesheet, qui sera en  général la date de la fin du mois',
                verbose_name='Date fin'),
        ),
        migrations.AlterField(
            model_name='simplifiedtimesheet',
            name='start_date',
            field=models.DateField(
                help_text='Date de début de votre timesheet, qui sera en  général la date de début du mois',
                verbose_name='Date début'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='other_details',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Autres détails'),
        ),
    ]
