# Generated by Django 2.2.3 on 2019-09-19 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0066_simplify_timesheet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='simplifiedtimesheet',
            options={'verbose_name': 'Temps de travail', 'verbose_name_plural': 'Temps de travail'},
        ),
        migrations.AlterModelOptions(
            name='simplifiedtimesheetdetail',
            options={'verbose_name': 'Détail temps de travail', 'verbose_name_plural': 'Détails temps de travail'},
        ),
        migrations.AddField(
            model_name='employee',
            name='provider_code',
            field=models.CharField(blank=True, help_text='Saisissez le code prestataire auprès de la C.N.S', max_length=30, verbose_name='Code prestataire'),
        ),
        migrations.AlterField(
            model_name='simplifiedtimesheet',
            name='employee',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='invoices.Employee'),
        ),
    ]
