# Generated by Django 2.2.7 on 2019-11-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0067_add_code_prestataire'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoiceitem',
            options={'verbose_name': "Mémoire d'honoraire", 'verbose_name_plural': "Mémoires d'honoraire"},
        ),
        migrations.AddField(
            model_name='carecode',
            name='participation',
            field=models.BooleanField(default=False, help_text='Si vous sélectionnez cette option la participation de 12% ne sera pas déduite de cette prestation', verbose_name='Participation forfaitaire non dûe'),
        ),
    ]
