# Generated by Django 2.2.7 on 2019-11-21 16:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import invoices.timesheet


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0069_add_participation_rename'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicHolidayCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_year', models.PositiveIntegerField(default=2019, validators=[django.core.validators.MinValueValidator(1984), invoices.timesheet.max_value_current_year])),
            ],
        ),
        migrations.CreateModel(
            name='PublicHolidayCalendarDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_date', models.DateField(help_text='toto', verbose_name='Date calendrier')),
                ('calendar_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.PublicHolidayCalendar')),
            ],
        ),
    ]
