# Generated by Django 2.2.7 on 2019-11-22 12:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0070_add_public_holidays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicholidaycalendar',
            name='calendar_year',
            field=models.PositiveIntegerField(default=2019),
        ),
        migrations.AlterField(
            model_name='publicholidaycalendardetail',
            name='calendar_date',
            field=models.DateField(help_text='Saisir la date calendrier du jour férié', verbose_name='Date calendrier'),
        ),
        migrations.CreateModel(
            name='EmployeeContractDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Date début période')),
                ('end_date', models.DateField(verbose_name='Date fin période')),
                ('number_of_hours', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(40)], verbose_name="Nombre d'heures")),
                ('employee_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.Employee')),
            ],
        ),
    ]
