# Generated by Django 2.2.7 on 2019-11-22 12:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0071_add_hours_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecontractdetail',
            name='end_date',
            field=models.DateField(blank=True, verbose_name='Date fin période'),
        ),
        migrations.AlterField(
            model_name='employeecontractdetail',
            name='number_of_hours',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(40)], verbose_name="Nombre d'heures par semaine"),
        ),
    ]
