# Generated by Django 2.2.7 on 2019-11-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0072_remove_null_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecontractdetail',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date fin période'),
        ),
    ]
