# Generated by Django 2.2.7 on 2019-11-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0073_remove_null_constraint2'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplifiedtimesheet',
            name='time_sheet_month',
            field=models.CharField(choices=[(1, 'Janvier'), (2, 'Février'), (11, 'Novembre'), (12, 'Décembre')], default=11, max_length=2),
        ),
        migrations.AddField(
            model_name='simplifiedtimesheet',
            name='time_sheet_year',
            field=models.PositiveIntegerField(default=2019),
        ),
    ]
