# Generated by Django 2.2.8 on 2019-12-17 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0076_remove_start_end_date_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplifiedtimesheet',
            name='time_sheet_month',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], default=12),
        ),
        migrations.AddConstraint(
            model_name='simplifiedtimesheet',
            constraint=models.UniqueConstraint(fields=('employee', 'time_sheet_year', 'time_sheet_month'), name='unique time sheet'),
        ),
    ]
