# Generated by Django 2.2.9 on 2019-12-19 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

import invoices


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoices', '0077_unique_timesheet_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_accepted', models.BooleanField(blank=True, default=False, verbose_name='Demande acceptée')),
                ('start_date', models.DateField(verbose_name='Date début')),
                ('end_date', models.DateField(verbose_name='Date fin')),
                ('half_day', models.BooleanField(verbose_name='Demi journée')),
                ('reason', models.PositiveSmallIntegerField(choices=[(1, 'Congés'), (2, 'Maladie'), (3, 'Formation')])),
                ('employee', invoices.db.models.fields.CurrentUserField(default=invoices.middleware.get_current_authenticated_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validator', to='invoices.Employee')),
            ],
            options={
                'verbose_name': "Demande d'absence",
                'verbose_name_plural': "Demandes d'absence",
            },
        ),
        migrations.AddConstraint(
            model_name='holidayrequest',
            constraint=models.UniqueConstraint(fields=('employee', 'start_date', 'end_date'), name='unique holiday request'),
        ),
    ]
