# Generated by Django 2.2.9 on 2019-12-20 18:59

from django.conf import settings
from django.db import migrations
import django.db.models.deletion

import invoices


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoices', '0078_create_holidayrequests'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplifiedtimesheet',
            name='user',
            field=invoices.db.fields.CurrentUserField(default=invoices.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
