# Generated by Django 3.0.7 on 2020-06-26 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
import gdstorage.storage
import invoices.models
import invoices.storages
import invoices.validators.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoices', '0080_2020_import_cns_prices_'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(help_text='Jour de lévénement', verbose_name='Jour de lévénement')),
                ('state', models.PositiveSmallIntegerField(choices=[(1, 'En attente de validation'), (2, 'Validé'), (3, 'Traité'), (4, 'Ignoré')])),
                ('notes', models.TextField(blank=True, help_text='Notes', null=True, verbose_name='Notes')),
                ('event_type', models.ForeignKey(help_text='Type dévénement', null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.EventType')),
                ('patient', models.ForeignKey(help_text='Veuillez séléctionner un patient', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Ptient', to='invoices.Patient')),
            ],
            options={
                'verbose_name': 'Scheduling',
                'verbose_name_plural': 'Scheduling',
            },
        ),
    ]
