# Generated by Django 3.0.8 on 2020-07-05 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0081_event_mgmt_and_cosmetics'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-id'], 'verbose_name': 'Event', 'verbose_name_plural': 'Event'},
        ),
        migrations.AddField(
            model_name='event',
            name='employees',
            field=models.ForeignKey(blank=True, help_text='Please select an employee', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_link_to_employee', to='invoices.Employee'),
        ),
        migrations.AddField(
            model_name='event',
            name='time_end_event',
            field=models.TimeField(blank=True, help_text='Event end time', null=True, verbose_name='Event end time'),
        ),
        migrations.AddField(
            model_name='event',
            name='time_start_event',
            field=models.TimeField(blank=True, help_text='Event start time', null=True, verbose_name='Event start time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(blank=True, help_text='Event type', null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.EventType', verbose_name='Event type'),
        ),
        migrations.AlterField(
            model_name='event',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Waiting for validation'), (2, 'Valid'), (3, 'Done'), (4, 'Ignored')], verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='to_be_generated',
            field=models.BooleanField(default=False, help_text='If checked, these type of events types will be generated auto.', verbose_name='To be generated'),
        ),
        migrations.AlterField(
            model_name='prestation',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prestations', to='invoices.Employee'),
        ),
        migrations.AlterField(
            model_name='simplifiedtimesheet',
            name='time_sheet_month',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], default=7),
        ),
    ]
