# Generated by Django 3.0.7 on 2020-06-26 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
import gdstorage.storage
import invoices.models
import invoices.storages
import invoices.validators.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoices', '0081_auto_20200626_1413'),
    ]

    operations = [
            migrations.AlterModelOptions(
                name='eventtype',
                options={'ordering': ['-id'], 'verbose_name': 'Scheduling Type', 'verbose_name_plural': 'Scheduling Type'},
            ),
            migrations.AlterField(
            model_name='event',
            name='patient',
            field=models.ForeignKey(blank=True, help_text='Veuillez séléctionner un patient', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Ptient', to='invoices.Patient'),
            )
        ]
