# Generated by Django 3.1.2 on 2020-10-21 11:42

from django.db import migrations, models
import django.db.models.deletion
import invoices.events


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0082_add_employee_to_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventList',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('invoices.event',),
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-time_start_event'], 'verbose_name': 'Event', 'verbose_name_plural': 'Event'},
        ),
        migrations.AddField(
            model_name='simplifiedtimesheet',
            name='extra_hours_paid',
            field=models.IntegerField(default=0, verbose_name='Hours paid to employee and to be deducted from total hours carried over'),
        ),
        migrations.AddField(
            model_name='simplifiedtimesheet',
            name='minutes_carried_over',
            field=models.IntegerField(default=0, verbose_name='Minutes carried over from previous months'),
        ),
        migrations.AlterField(
            model_name='event',
            name='employees',
            field=models.ForeignKey(blank=True, help_text='Please select an employee', limit_choices_to=invoices.events.limit_to_active_employees, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_link_to_employee', to='invoices.employee'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(help_text='Event type', on_delete=django.db.models.deletion.CASCADE, to='invoices.eventtype', verbose_name='Event type'),
        ),
        migrations.AlterField(
            model_name='prestation',
            name='employee',
            field=models.ForeignKey(blank=True, default='auth.User', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prestations', to='invoices.employee'),
        ),
        migrations.AlterField(
            model_name='simplifiedtimesheet',
            name='time_sheet_month',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], default=10),
        ),
    ]
