# Generated by Django 3.1.3 on 2020-11-04 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import invoices.events


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoices', '0082_add_employee_to_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventList',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('invoices.event',),
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-time_start_event'], 'verbose_name': 'Event', 'verbose_name_plural': 'Event'},
        ),
        migrations.AddField(
            model_name='holidayrequest',
            name='request_creator',
            field=invoices.db.fields.CurrentUserField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holiday_request_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employee',
            name='provider_code',
            field=models.CharField(blank=True, help_text='Enter the service provider code at the C.N.S', max_length=30, verbose_name='Provider code'),
        ),
        migrations.AlterField(
            model_name='event',
            name='employees',
            field=models.ForeignKey(blank=True, help_text='Please select an employee', limit_choices_to=invoices.events.limit_to_active_employees, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_link_to_employee', to='invoices.employee'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(help_text='Event type', on_delete=django.db.models.deletion.CASCADE, to='invoices.eventtype', verbose_name='Event type'),
        ),
        migrations.AlterField(
            model_name='prestation',
            name='employee',
            field=models.ForeignKey(blank=True, default='auth.User', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prestations', to='invoices.employee'),
        ),
        migrations.AlterField(
            model_name='simplifiedtimesheet',
            name='time_sheet_month',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], default=11),
        ),
    ]
