# Generated by Django 3.1.3 on 2020-11-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0083_add_request_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidayrequest',
            name='force_creation',
            field=models.BooleanField(default=False),
        ),
    ]
