# Generated by Django 3.1.3 on 2020-11-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0084_add_force_request_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='birth_place',
            field=models.CharField(blank=True, help_text='Enter the City / Country of Birth', max_length=30, verbose_name='Birth Place'),
        ),
        migrations.AddField(
            model_name='employee',
            name='driving_licence_number',
            field=models.CharField(blank=True, help_text='Enter the driver licence number', max_length=20, verbose_name='Driver Licence Number'),
        ),
        migrations.AlterField(
            model_name='holidayrequest',
            name='force_creation',
            field=models.BooleanField(default=False, help_text='Si vous êtes manager vous pouvez forcer la création de congés même si conflits avec d#autre employés'),
        ),
    ]
