# Generated by Django 3.1.4 on 2020-12-26 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0085_drivers_lcnce_birth_place_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('licence_plate', models.CharField(max_length=8)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.AlterField(
            model_name='simplifiedtimesheet',
            name='time_sheet_month',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], default=12),
        ),
        migrations.CreateModel(
            name='ExpenseCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('number', models.CharField(default='XX1111', max_length=20)),
                ('pin', models.CharField(default='1111', max_length=4)),
                ('car_link', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.car')),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
    ]
