# Generated by Django 3.1.5 on 2021-01-28 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0088_add_address_to_evts'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidayrequest',
            name='request_status',
            field=models.CharField(choices=[('PNDG', 'Pending'), ('REF', 'Refused'), ('OK', 'Accepted')], default='PNDG', max_length=4),
        ),
        migrations.AddField(
            model_name='holidayrequest',
            name='validator_notes',
            field=models.TextField(blank=True, help_text='Notes', null=True, verbose_name='Notes Validateur'),
        ),
    ]
