# Generated by Django 3.1.5 on 2021-01-30 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0089_add_holiday_request_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holidayrequest',
            name='request_accepted',
        ),
    ]
