# Generated by Django 3.1.6 on 2021-02-02 17:41

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0090_remove_request_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='abbreviation',
            field=models.CharField(default='XXX', help_text='Enter employee abbreviation, must be unique accross company', max_length=3, verbose_name='Abbreviation'),
        ),
        migrations.AddField(
            model_name='employee',
            name='color_cell',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
        migrations.AddField(
            model_name='employee',
            name='color_text',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
        migrations.AlterField(
            model_name='simplifiedtimesheet',
            name='time_sheet_month',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], default=2),
        ),
    ]
