# Generated by Django 3.1.6 on 2021-02-02 23:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0091_employee_color_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='calendar_id',
            field=models.CharField(blank=True, default='0', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='calendar_url',
            field=models.URLField(blank=True, default='http://a.sur.lu', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.CharField(default='ui', max_length=30),
        ),
        migrations.AddField(
            model_name='event',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
