# Generated by Django 3.1.6 on 2021-02-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0092_add_event_creation_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalization',
            name='end_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Date de fin'),
        ),
    ]
