# Generated by Django 3.1.6 on 2021-02-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0092_add_event_creation_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='invoice_nurse_code',
            field=models.CharField(choices=[('MAIN', '300744-44'), ('BIS', '300744-44')], default='MAIN', max_length=10),
        ),
    ]
