# Generated by Django 3.1.7 on 2021-02-19 17:29

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import invoices.models
from constance import config

from invoices.modelspackage.invoice import get_default_invoicing_details


def create_default_invoicing_details_based_on_config_constance(apps, schema_editor):
    _InvoicingDetails = apps.get_model('invoices', 'InvoicingDetails')
    default_invoicing_detail = _InvoicingDetails()
    default_invoicing_detail.provider_code = config.MAIN_NURSE_CODE
    default_invoicing_detail.name = config.NURSE_NAME
    default_invoicing_detail.address = config.NURSE_ADDRESS
    default_invoicing_detail.zipcode_city = config.NURSE_ZIP_CODE_CITY
    default_invoicing_detail.phone_number = config.NURSE_PHONE_NUMBER
    default_invoicing_detail.bank_account = config.MAIN_BANK_ACCOUNT
    default_invoicing_detail.default_invoicing = True
    default_invoicing_detail.save()


def set_default_invoice_item_details_for_previously_invoices(apps, schema_editor):
    _InvoicingDetails = apps.get_model('invoices', 'InvoicingDetails')
    default_invoicing_detail = _InvoicingDetails.objects.get(default_invoicing=True)
    _InvoiceItemModel = apps.get_model('invoices', 'InvoiceItem')
    for invoice_item in _InvoiceItemModel.objects.all():
        invoice_item.invoice_details = default_invoicing_detail
        invoice_item.save()
        print("adding %s to : %s" % (default_invoicing_detail, invoice_item))


class Migration(migrations.Migration):
    dependencies = [
        ('invoices', '0093_add_alternative_nurse_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoicingDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('address', models.TextField(max_length=50)),
                ('zipcode_city', models.CharField(max_length=20)),
                ('country', django_countries.fields.CountryField(blank=True, default='LU', max_length=2, null=True)),
                ('phone_number', models.CharField(max_length=30)),
                ('email_address', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('bank_account', models.CharField(max_length=50)),
                ('default_invoicing', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Détail de facturation',
                'verbose_name_plural': 'Détail de facturation',
                'ordering': ['-id'],
            },
        ),
        migrations.RunPython(create_default_invoicing_details_based_on_config_constance),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='invoice_nurse_code',
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='invoice_details',
            field=models.ForeignKey(default=get_default_invoicing_details,on_delete=django.db.models.deletion.PROTECT,
                                    related_name='invoicing_details_link',
                                    to='invoices.invoicingdetails'),
        ),
        migrations.RunPython(set_default_invoice_item_details_for_previously_invoices),

    ]
