# Generated by Django 3.1.7 on 2021-02-26 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0095_add_anamnesis'),
        ('invoices', '0093_hospi_end_date_can_be_null'),
    ]

    operations = [
    ]
