# Generated by Django 3.1.7 on 2021-02-26 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0096_merge_20210226_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='login_time',
            field=models.DateTimeField(null=True),
        ),
    ]
