# Generated by Django 3.1.7 on 2021-03-09 11:34

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    def migrate_from_gdrive_to_cloudinary(apps, schema_editor):
        _MedicalPrescription = apps.get_model('invoices', 'MedicalPrescription')
        for medical_prescription in _MedicalPrescription.objects.all():
            medical_prescription.image_file = medical_prescription.file
            medical_prescription.save()
            print("migrating %s to : %s" % (medical_prescription.file, medical_prescription.image_file))


    dependencies = [
        ('invoices', '0097_add_ins_dep_decision_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalprescription',
            name='image_file',
            field=cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='Scan or picture'),
        ),
        migrations.AlterField(
            model_name='patientanamnesis',
            name='pathologies',
            field=models.TextField(blank=True, default=None, max_length=500, null=True, verbose_name='Pathologies'),
        ),
        migrations.AlterField(
            model_name='simplifiedtimesheet',
            name='time_sheet_month',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], default=3),
        ),

        migrations.RunPython(migrate_from_gdrive_to_cloudinary),
    ]
