# Generated by Django 3.1.7 on 2021-03-09 18:19
from django.core.files.base import ContentFile
from django.core.files.storage import FileSystemStorage
from django.db import migrations, models


class Migration(migrations.Migration):

    def migrate_from_gdrive_to_localstorage(apps, schema_editor):
        _MedicalPrescription = apps.get_model('invoices', 'MedicalPrescription')
        for medical_prescription in _MedicalPrescription.objects.all():
            if medical_prescription.file and medical_prescription.file.url and not medical_prescription.p_file:
                local_storage = FileSystemStorage()
                newfile = ContentFile(medical_prescription.file.read())
                relative_path = local_storage.save(medical_prescription.file.name, newfile)
                print("relative path %s" % relative_path)
                medical_prescription.p_file = relative_path
                medical_prescription.save()
                print("migrating %s to : %s" % (medical_prescription.file, medical_prescription.image_file))

    dependencies = [
        ('invoices', '0098_cloudinary_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalprescription',
            name='image_file',
        ),
        migrations.AddField(
            model_name='medicalprescription',
            name='p_file',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='prescriptions', verbose_name='Scan or picture'),
        ),
        migrations.RunPython(migrate_from_gdrive_to_localstorage),
    ]
