# Generated by Django 3.1.7 on 2021-03-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0098_cloudinary_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientanamnesis',
            name='allergies',
            field=models.TextField(blank=True, default=None, max_length=250, null=True, verbose_name='Allergies'),
        ),
        migrations.AlterField(
            model_name='patientanamnesis',
            name='shopping_management_desc',
            field=models.TextField(blank=True, default=None, max_length=250, null=True, verbose_name='Description'),
        ),
    ]
