# Generated by Django 3.1.7 on 2021-03-25 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0099_widens_anamnesis_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateField(blank=True, default=None, null=True)),
                ('invoice_list', models.CharField(max_length=200)),
            ],
        ),
    ]
