# Generated by Django 3.2 on 2021-04-12 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0101_add_gender_to_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiographyHabits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habit_type', models.CharField(blank=True, choices=[('MORNING', 'Levé'), ('SLEEP', 'Coucher'), ('BRK_FST', 'Petit Déjeuner'), ('LNCH', 'Déjeuner'), ('DNR', 'Diner')], default=None, max_length=7, null=True, verbose_name='Type')),
                ('habit_time', models.TimeField(verbose_name='Heure')),
                ('habit_ritual', models.CharField(max_length=50, verbose_name='Rite')),
                ('habit_preferences', models.CharField(max_length=50, verbose_name='Préférences')),
                ('preferred_drinks', models.TextField(max_length=250, verbose_name='Boissons préfèrées')),
                ('biography', models.ForeignKey(blank=True, default=None, help_text='Veuillez saisir les habitudes du bénéficiaire', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='habit_patient_biography', to='invoices.patientanamnesis')),
            ],
            options={
                'verbose_name': 'Habitudes',
                'verbose_name_plural': 'Habitudes',
                'ordering': ['-id'],
            },
        ),
    ]
