# Generated by Django 3.2 on 2021-04-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0102_patient_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biographyhabits',
            name='preferred_drinks',
        ),
        migrations.AddField(
            model_name='patientanamnesis',
            name='preferred_drinks',
            field=models.TextField(blank=True, default=None, max_length=250, null=True, verbose_name='Boissons préfèrées'),
        ),
    ]
