# Generated by Django 3.2 on 2021-04-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0103_patient_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientanamnesis',
            name='bio_highlights',
            field=models.TextField(blank=True, default=None, help_text='Quelles sont les éléments marquants de votre vie, qui sont importants pour bien vous soigner ?', max_length=200, null=True, verbose_name='Important'),
        ),
        migrations.AddField(
            model_name='patientanamnesis',
            name='dressing_habits',
            field=models.TextField(blank=True, default=None, help_text='Goûts vestimentaires', max_length=100, null=True, verbose_name='Habillements'),
        ),
        migrations.AddField(
            model_name='patientanamnesis',
            name='family_ties',
            field=models.TextField(blank=True, default=None, max_length=200, null=True, verbose_name='Famille'),
        ),
        migrations.AddField(
            model_name='patientanamnesis',
            name='friend_ties',
            field=models.TextField(blank=True, default=None, max_length=200, null=True, verbose_name='Amis'),
        ),
        migrations.AddField(
            model_name='patientanamnesis',
            name='general_wishes',
            field=models.TextField(blank=True, default=None, max_length=250, null=True, verbose_name='Souhaits'),
        ),
        migrations.AddField(
            model_name='patientanamnesis',
            name='important_persons_ties',
            field=models.TextField(blank=True, default=None, max_length=200, null=True, verbose_name='Personnes importantes'),
        ),
        migrations.AddField(
            model_name='patientanamnesis',
            name='occupation_habits',
            field=models.TextField(blank=True, default=None, help_text='Profession, loisirs, sports, lecture, TV, musique, cinéma, sorties...', max_length=250, null=True, verbose_name='Occupations'),
        ),
        migrations.AddField(
            model_name='patientanamnesis',
            name='shower_habits',
            field=models.TextField(blank=True, default=None, help_text='douche, lavé, bain', max_length=100, null=True, verbose_name='Se soigner'),
        ),
    ]
