# Generated by Django 3.2 on 2021-04-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0104_patient_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidayrequest',
            name='requested_period',
            field=models.CharField(choices=[('MRNG', 'Matin'), ('EVNG', 'Soir'), ('FULL', 'Journée entière')], default='FULL', max_length=4),
        ),
    ]
