# Generated by Django 3.2 on 2021-04-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0105_holiday_request_refine_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holidayrequest',
            name='half_day',
        ),
        migrations.AlterField(
            model_name='holidayrequest',
            name='requested_period',
            field=models.CharField(choices=[('MRNG', 'Matin'), ('EVNG', 'Soir'), ('FULL', 'Journée entière')], default='FULL', max_length=4, verbose_name='Période'),
        ),
    ]
