# Generated by Django 3.2.7 on 2021-09-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0107_add_patient_parameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Adresse'),
        ),
    ]
