# Generated by Django 3.2.8 on 2021-10-12 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '00109_2021_october_import_cns_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='access_card_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Carte Voiture'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='simplifiedtimesheet',
            name='time_sheet_month',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], default=10),
        ),
        migrations.CreateModel(
            name='AssignedAdditionalEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_additional_employee', models.ForeignKey(blank=True, default=None, help_text='Please enter employee', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_employees_to_event', to='invoices.employee', verbose_name='Soignant')),
                ('event_assigned_to', models.ForeignKey(blank=True, default=None, help_text='Please enter xxx', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_assigned', to='invoices.event')),
            ],
            options={
                'verbose_name': 'Invité Traitant',
                'verbose_name_plural': 'Invités Traitant',
            },
        ),
    ]
