# Generated by Django 3.2.9 on 2021-11-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0110_additional_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_under_dependence_insurance',
            field=models.BooleanField(default=False, verbose_name='Assurance dépendance'),
        ),
        migrations.AlterField(
            model_name='simplifiedtimesheet',
            name='time_sheet_month',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], default=11),
        ),
    ]
