# Generated by Django 4.0.2 on 2022-02-03 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import invoices.db.fields
import invoices.middleware


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoices', '0111_add_dep_insurance_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplifiedtimesheet',
            name='extra_hours_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Balance des heures supp. non soldées'),
        ),
        migrations.AddField(
            model_name='simplifiedtimesheet',
            name='extra_hours_paid_current_month',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Heures supp. payées ou récupérées pour le mois courant'),
        ),
        migrations.AlterField(
            model_name='carecode',
            name='exclusive_care_codes',
            field=models.ManyToManyField(blank=True, to='invoices.CareCode'),
        ),
        migrations.AlterField(
            model_name='holidayrequest',
            name='employee',
            field=invoices.db.fields.CurrentUserField(default=invoices.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='holidayrequest',
            name='reason',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Congés'), (2, 'Maladie'), (3, 'Formation'), (4, 'Desiderata'), (5, 'Exceptionnel')]),
        ),
        migrations.AlterField(
            model_name='holidayrequest',
            name='request_creator',
            field=invoices.db.fields.CurrentUserField(default=invoices.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holiday_request_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publicholidaycalendar',
            name='calendar_year',
            field=models.PositiveIntegerField(default=2022),
        ),
        migrations.AlterField(
            model_name='simplifiedtimesheet',
            name='time_sheet_month',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], default=2),
        ),
        migrations.AlterField(
            model_name='simplifiedtimesheet',
            name='time_sheet_year',
            field=models.PositiveIntegerField(default=2022),
        ),
        migrations.AlterField(
            model_name='simplifiedtimesheet',
            name='user',
            field=invoices.db.fields.CurrentUserField(default=invoices.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
