# Generated by Django 4.0.2 on 2022-02-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0112_extra_hours_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carecode',
            name='name',
            field=models.TextField(max_length=320),
        ),
        migrations.AlterField(
            model_name='simplifiedtimesheet',
            name='extra_hours_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Ce champ est calculé mais vous pouvez quand même écraser la valeur si vous êtes admin.\nIl reporte le total des heures suppl. (ou déficit) du mois M - 1.\nIl est (re)calculé à chaque fois que l'on valide un Temps de Travail et la formule : Hours should work TS(M-1) + Balance des heures supp. non soldées - Heures supp. payées ou récupérées pour le mois courant", max_digits=5, verbose_name='Balance des heures supp. non soldées'),
        ),
    ]
