# Generated by Django 4.0.5 on 2022-06-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0117_cleanup'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposition',
            name='is_involved_in_health_care',
            field=models.BooleanField(default=True, verbose_name='Impliqué dans les soins'),
        ),
        migrations.AddField(
            model_name='patient',
            name='additional_details',
            field=models.TextField(blank=True, default=None, help_text='Vous pouvez mettre par exemple les numéros de carte adapto ou tout autre info utile.', max_length=500, null=True, verbose_name='Détails additionels'),
        ),
    ]
