# Generated by Django 4.0.5 on 2022-06-28 14:33

from django.db import migrations, models
import django.db.models.deletion
import invoices.holidays


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0120_enlarge_extra_hours_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='medical_prescription',
            field=models.ForeignKey(blank=True, help_text='Please choose a Medical Prescription', limit_choices_to={'is_under_dependence_insurance': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='invoices.medicalprescription'),
        ),
        migrations.CreateModel(
            name='AbsenceRequestFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_description', models.CharField(max_length=30, verbose_name='description')),
                ('file_upload', models.FileField(blank=True, null=True, upload_to=invoices.holidays.update_absence_request_filename)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.holidayrequest')),
            ],
        ),
    ]
