# Generated by Django 4.0.5 on 2022-06-28 14:57

from django.db import migrations, models
import django.db.models.deletion
import invoices.employee


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0121_holiday_request_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAdminFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_description', models.CharField(max_length=50, verbose_name='description')),
                ('file_upload', models.FileField(blank=True, null=True, upload_to=invoices.employee.update_filename)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.employee')),
            ],
        ),
    ]
