# Generated by Django 4.0.6 on 2022-07-05 11:22

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0123_employee_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='access_card_code',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Code Carte Voiture'),
        ),
        migrations.AddField(
            model_name='employee',
            name='citizenship',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='end_trial_period',
            field=models.DateField(blank=True, null=True, verbose_name="Fin période d'essai"),
        ),
        migrations.AddField(
            model_name='employee',
            name='sn_code',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Matricule sécurité sociale'),
        ),
        migrations.AddField(
            model_name='employeecontractdetail',
            name='contract_type',
            field=models.CharField(blank=True, choices=[('CDD', 'CDD'), ('CDI', 'CDI'), ('STG', 'Stage')], default='CDI', max_length=10, null=True, verbose_name='Type contrat'),
        ),
        migrations.AddField(
            model_name='employeecontractdetail',
            name='monthly_wage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Salaire Mensuel'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='bank_account_number',
            field=models.CharField(blank=True, help_text='Code BIC + IBAN', max_length=50, verbose_name='Numéro de compte IBAN'),
        ),
        migrations.AlterField(
            model_name='simplifiedtimesheet',
            name='time_sheet_month',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], default=7),
        ),
    ]
