# Generated by Django 4.0.6 on 2022-07-12 11:49

from django.db import migrations, models
import invoices.models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0124_enrich_employee_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalprescription',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to=invoices.models.update_medical_prescription_filename),
        ),
    ]
