# Generated by Django 4.0.6 on 2022-07-14 15:56

from django.db import migrations, models
import django.db.models.deletion

from invoices.enums.event import EventTypeEnum as _EventTypeEnum


class Migration(migrations.Migration):

    def change_state_from_event_to_event_enum(apps, schema_editor):
        _Event = apps.get_model('invoices', 'Event')
        for event in _Event.objects.all():
            if 'soin' == event.event_type.name:
                event.event_type_enum = _EventTypeEnum.CARE
            elif 'Birthdays' == event.event_type.name:
                event.event_type_enum = _EventTypeEnum.BIRTHDAY
            else:
                event.event_type_enum = _EventTypeEnum.GENERIC
            event.save()
            print("*** migrated event %s from : %s to %s" % (event, event.event_type, event.event_type_enum))

    dependencies = [
        ('invoices', '0125_upload_medical_prescription_to_s3'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventWeekList',
            fields=[
            ],
            options={
                'verbose_name': "Nouveau Plannig (Ne modifiez pas les événements à partir d'ici)",
                'verbose_name_plural': "Nouveaux Plannigs (Ne modifiez pas les événements à partir d'ici)",
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('invoices.event',),
        ),
        migrations.AddField(
            model_name='event',
            name='event_report',
            field=models.TextField(blank=True, help_text='A remplir une fois le soin terminé', null=True, verbose_name='Rapport de soin'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type_enum',
            field=models.CharField(choices=[('BIRTHDAY', 'Birthday'), ('CARE', 'Soin'), ('GENERIC', 'Général (non soin)')], default='CARE', max_length=10, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(blank=True, help_text='Event type', null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.eventtype', verbose_name='Event type'),
        ),
        migrations.RunPython(change_state_from_event_to_event_enum)
    ]
