# Generated by Django 4.0.6 on 2022-07-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0126_event_type_enum'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventlist',
            options={'verbose_name': 'Mes tâches', 'verbose_name_plural': 'Planning tâches à valider'},
        ),
        migrations.AddField(
            model_name='medicalprescription',
            name='notes',
            field=models.TextField(blank=True, help_text="Veuillez mettre le text de l'ordonnance ou des notes", max_length=1000, null=True, verbose_name='Notes ou remarques'),
        ),
        migrations.AddField(
            model_name='medicalprescription',
            name='thumbnail_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
