# Generated by Django 4.0.6 on 2022-07-27 11:10

from django.db import migrations, models
import invoices.models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0127_ordo_thumbnail_and_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type_enum',
            field=models.CharField(choices=[('BIRTHDAY', 'Birthday'), ('CARE', 'Soin'), ('ASS_DEP', 'Soin Assurance dépendance'), ('GENERIC', 'Général (non soin)')], default='CARE', max_length=10, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='event',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Waiting for validation'), (2, 'Valid'), (3, 'Done'), (4, 'Ignored'), (5, 'Not Done')], verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='medicalprescription',
            name='notes',
            field=models.TextField(blank=True, help_text="Veuillez mettre le text de l'ordonnance ou des notes concernant les soins prescrits", max_length=1000, null=True, verbose_name='Notes ou remarques'),
        ),
        migrations.AlterField(
            model_name='medicalprescription',
            name='thumbnail_img',
            field=models.ImageField(blank=True, null=True, upload_to=invoices.models.update_medical_prescription_filename, verbose_name='Aperçu'),
        ),
    ]
