# Generated by Django 4.1 on 2022-08-16 16:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0129_aai_and_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplifiedtimesheet',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date création'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='simplifiedtimesheet',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour'),
        ),
    ]
