# Generated by Django 4.1.3 on 2022-11-25 17:19

from django.db import migrations, models
import django.db.models.deletion
import invoices.events


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0131_add_evs_to_params'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=invoices.events.update_report_picture_filename, validators=[invoices.events.validate_image])),
                ('event', models.ForeignKey(help_text='Here, you can upload pictures of the patient if needed', on_delete=django.db.models.deletion.CASCADE, related_name='report_pictures', to='invoices.event')),
            ],
            options={
                'verbose_name': 'Image attachée au rapport',
                'verbose_name_plural': 'Images attachées au rapport',
            },
        ),
    ]
