# Generated by Django 4.1.3 on 2022-11-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0132_add_report_picture_to_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportpicture',
            name='description',
            field=models.TextField(default='', help_text='Please, give a decription of the uploaded image.', max_length=250, verbose_name='Description'),
        ),
    ]
