# Generated by Django 4.1.4 on 2022-12-19 17:13

from django.db import migrations, models
import invoices.employee


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0134_yale_door_setup'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='avatar',
            field=models.ImageField(blank=True, help_text='You can attach the scan of the declaration', null=True, upload_to=invoices.employee.avatar_storage_location, validators=[invoices.employee.validate_avatar]),
        ),
        migrations.AddField(
            model_name='employee',
            name='bio',
            field=models.TextField(default='Fill in your bio', max_length=200, verbose_name='Bio'),
        ),
        migrations.AddField(
            model_name='employee',
            name='to_be_published_on_www',
            field=models.BooleanField(blank=True, help_text='If checked then bio and avatar fields become mandatory', null=True, verbose_name='Public Profile'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='birth_place',
            field=models.CharField(blank=True, help_text='Enter the City / Country of Birth', max_length=50, verbose_name='Birth Place'),
        ),
        migrations.AlterField(
            model_name='simplifiedtimesheet',
            name='time_sheet_month',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], default=12),
        ),
    ]
