# Generated by Django 4.1.5 on 2023-01-18 13:57

from django.db import migrations, models
import invoices.resources


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0136_add_do_not_notify_check_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='registration_card',
            field=models.FileField(blank=True, help_text='You can attach the scan of the registration card of the car', null=True, upload_to=invoices.resources.registration_card_storage_location),
        ),
        migrations.AddField(
            model_name='car',
            name='vin_number',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
