# Generated by Django 4.1.5 on 2023-01-18 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0137_create_vin_and_reg_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceItemEmailLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('cc', models.CharField(blank=True, max_length=200)),
                ('bcc', models.CharField(blank=True, max_length=200)),
                ('attachments', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(blank=True, max_length=200)),
                ('error', models.TextField(blank=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='invoices.invoiceitem')),
            ],
        ),
    ]
