# Generated by Django 4.1.5 on 2023-01-22 21:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0138_create_email_logs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='birth date'),
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('MAL', 'Male'), ('FEM', 'Female'), ('OTH', 'Other')], default=None, max_length=5, null=True, verbose_name='Sex'),
        ),
        migrations.AddField(
            model_name='employeecontractdetail',
            name='index',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Index'),
        ),
        migrations.AddField(
            model_name='employeecontractdetail',
            name='number_of_days_holidays',
            field=models.PositiveSmallIntegerField(default=26, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(36)], verbose_name='Nombre de jours de congés'),
            preserve_default=False,
        ),
    ]
