# Generated by Django 4.1.5 on 2023-01-24 16:15

from django.db import migrations, models
import django.db.models.deletion
import invoices.models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0139_enrich_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='abbreviation',
            field=models.CharField(default='XXX', help_text='Enter employee abbreviation, must be unique across company', max_length=3, verbose_name='Abbreviation'),
        ),
        migrations.CreateModel(
            name='PatientAdminFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_description', models.CharField(max_length=50, verbose_name='description')),
                ('file_date', models.DateField(blank=True, null=True, verbose_name='date du fichier')),
                ('file_upload', models.FileField(blank=True, null=True, upload_to=invoices.models.update_patient_admin_filename)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.patient')),
            ],
        ),
    ]
