# Generated by Django 4.1.5 on 2023-01-25 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0141_expand_contract_details_for_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeecontractdetail',
            name='salary_index',
        ),
    ]
