# Generated by Django 4.1.5 on 2023-01-28 14:00

from django.db import migrations, models
import django.db.models.deletion
import invoices.events


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0142_expand_contract_details_for_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='employees',
            field=models.ForeignKey(blank=True, help_text='Please select an employee', limit_choices_to=invoices.events.limit_to_active_employees, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='event_link_to_employee', to='invoices.employee'),
        ),
    ]
