# Generated by Django 4.1.5 on 2023-01-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0143_unlink_employee_deletion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecontractdetail',
            name='employee_trial_period_text',
            field=models.TextField(blank=True, max_length=800, null=True, verbose_name="Texte période d'essai"),
        ),
    ]
