# Generated by Django 4.1.5 on 2023-01-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0144_enlarge_trial_period_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecontractdetail',
            name='anniversary_career_rank',
            field=models.DateField(blank=True, null=True, verbose_name='Date anniversaire grade'),
        ),
        migrations.AddField(
            model_name='employeecontractdetail',
            name='career_rank',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Grade'),
        ),
    ]
