# Generated by Django 4.1.5 on 2023-01-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0145_add_career_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecontractdetail',
            name='weekly_work_organization',
            field=models.TextField(blank=True, help_text='Veuillez saisir ce champ sous format: 8h/j 5 jours par semaine', max_length=80, null=True, verbose_name='Organisation du travail hebdomadaire'),
        ),
        migrations.AlterField(
            model_name='employeecontractdetail',
            name='career_rank',
            field=models.CharField(blank=True, help_text='Sous format Grade / Ancienneté Carrière', max_length=10, null=True, verbose_name='Grade'),
        ),
    ]
