# Generated by Django 4.1.5 on 2023-01-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0146_add_work_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecontractdetail',
            name='index',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Index'),
        ),
    ]
