# Generated by Django 4.1.6 on 2023-02-05 15:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0147_fix_index_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecontractdetail',
            name='number_of_days_holidays',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(37)], verbose_name='Nombre de jours de congés'),
        ),
        migrations.AlterField(
            model_name='patientanamnesis',
            name='civil_status',
            field=models.CharField(blank=True, choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('WIDOW', 'Widow'), ('PACS', 'Pacs'), ('DIV', 'Divorced'), ('SEP', 'Separated'), ('OTH', 'Other')], default=None, max_length=7, null=True, verbose_name='État civil'),
        ),
        migrations.AlterField(
            model_name='patientanamnesis',
            name='mobilization',
            field=models.CharField(blank=True, choices=[('AUTNM', 'Autonomous'), ('TCNQ', 'With technical help'), ('TRD', 'With third party'), ('BD', 'Bedridden'), ('TCNQ_TRD', 'Both Technical help and third party')], default=None, max_length=15, null=True, verbose_name='Mobilisation'),
        ),
        migrations.AlterField(
            model_name='patientanamnesis',
            name='remote_alarm',
            field=models.CharField(blank=True, choices=[('RK', 'Roude Knap'), ('SDHM', 'Secher Doheem'), ('HLP', 'Help'), ('OTH', 'Other')], default=None, max_length=4, null=True, verbose_name='Alarme'),
        ),
        migrations.AlterField(
            model_name='simplifiedtimesheet',
            name='time_sheet_month',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], default=2),
        ),
    ]
