# Generated by Django 4.1.7 on 2023-02-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0148_anamnesise_enchancements'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='virtual_career_anniversary_date',
            field=models.DateField(blank=True, help_text='Pour les carrières sous convention SAS', null=True, verbose_name='Date anniversaire carrière virtuelle'),
        ),
        migrations.AddField(
            model_name='employeeadminfile',
            name='document_expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'expiration du document"),
        ),
        migrations.AlterField(
            model_name='employeeadminfile',
            name='file_description',
            field=models.CharField(max_length=60, verbose_name='description'),
        ),
    ]
