# Generated by Django 4.1.7 on 2023-03-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0152_more_details_invoicing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicingdetails',
            name='aa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Autorisation ministère de la famille activités aides à domicile'),
        ),
        migrations.AlterField(
            model_name='invoicingdetails',
            name='af',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Autorisation ministère de la famille activités soins à domicile'),
        ),
        migrations.AlterField(
            model_name='invoicingdetails',
            name='rc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Registre de commerce'),
        ),
    ]
