# Generated by Django 4.1.7 on 2023-03-12 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0153_more_details_invoicing'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientanamnesis',
            name='birth_place',
            field=models.CharField(blank=True, help_text='Enter the City / Country of Birth', max_length=50, verbose_name='Birth Place'),
        ),
        migrations.AddField(
            model_name='patientanamnesis',
            name='contract_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='contracts', verbose_name='Contrat'),
        ),
        migrations.AddField(
            model_name='patientanamnesis',
            name='contract_signed_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Date de signature du contrat'),
        ),
        migrations.AddField(
            model_name='patientanamnesis',
            name='start_date_of_care',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Date de début de prise en charge'),
        ),
    ]
