# Generated by Django 4.1.7 on 2023-03-12 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0154_enrich_anamnesis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biographyhabits',
            name='biography',
        ),
        migrations.RemoveField(
            model_name='contactperson',
            name='patient_anamnesis',
        ),
        migrations.RemoveField(
            model_name='dependenceinsurance',
            name='dep_anamnesis',
        ),
        migrations.RemoveField(
            model_name='otherstakeholder',
            name='stakeholder_anamnesis',
        ),
        migrations.RemoveField(
            model_name='patientanamnesis',
            name='patient',
        ),
        migrations.DeleteModel(
            name='AssignedPhysician',
        ),
        migrations.DeleteModel(
            name='BiographyHabits',
        ),
        migrations.DeleteModel(
            name='ContactPerson',
        ),
        migrations.DeleteModel(
            name='DependenceInsurance',
        ),
        migrations.DeleteModel(
            name='OtherStakeholder',
        ),
        migrations.DeleteModel(
            name='PatientAnamnesis',
        ),
    ]
