# Generated by Django 4.1.7 on 2023-03-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0155_enrich_anamnesis'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='miscellaneous',
            field=models.TextField(default='Code Pin tél:...etc', max_length=200, verbose_name='Divers'),
        ),
        migrations.AddField(
            model_name='employeecontractdetail',
            name='responsibility_bonus',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Index'),
        ),
    ]
