# Generated by Django 4.1.7 on 2023-03-21 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0156_employee_data_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceItemPrescriptionsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='invoices.invoiceitem')),
            ],
        ),
    ]
