# Generated by Django 4.1.7 on 2023-03-21 16:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0158_can_associate_more_than_one_medical_prescription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoiceitemprescriptionslist',
            options={'verbose_name': 'Liste des ordonnances', 'verbose_name_plural': 'Liste des ordonnances'},
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='invoiceitemprescriptionslist',
            name='medical_prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='med_prescription_multi_invoice_items', to='invoices.medicalprescription', verbose_name='Ordonnance'),
        ),
    ]
