# Generated by Django 4.1.7 on 2023-03-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0159_can_associate_more_than_one_medical_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_eligible_to_parameter_surveillance',
            field=models.BooleanField(default=False, verbose_name='Suivre Paramètres'),
        ),
    ]
