# Generated by Django 4.1.7 on 2023-03-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependence', '0059_associate_careitems_to_careplan'),
        ('invoices', '0160_new_field_on_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='long_term_care_items',
            field=models.ManyToManyField(blank=True, help_text='Please select the long term care items', to='dependence.longtermcareitem', verbose_name='Soins assurance Dépendance'),
        ),
    ]
