# Generated by Django 4.1.7 on 2023-03-22 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dependence', '0059_associate_careitems_to_careplan'),
        ('invoices', '0161_associate_careitems_to_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='long_term_care_items',
        ),
        migrations.AddField(
            model_name='event',
            name='care_plan_detail',
            field=models.ForeignKey(blank=True, help_text='Choisissez un plan de soin', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='event_link_to_care_plan_detail', to='dependence.careplandetail'),
        ),
    ]
