# Generated by Django 4.1.8 on 2023-04-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0163_ajouter_forfait_hebdo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validitydate',
            name='gross_amount',
            field=models.DecimalField(decimal_places=6, max_digits=10, verbose_name='montant brut'),
        ),
    ]
