# Generated by Django 4.1.8 on 2023-04-27 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0164_add_more_decimals_to_care_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doorevent',
            name='employee',
        ),
        migrations.DeleteModel(
            name='YaleAuthToken',
        ),
        migrations.DeleteModel(
            name='DoorEvent',
        ),
    ]
