# Generated by Django 4.1.8 on 2023-04-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0165_cleanup'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='invoxia_identifier',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
