# Generated by Django 4.1.8 on 2023-04-29 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0167_add_patient_exit_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='charge_level',
        ),
    ]
