# Generated by Django 4.1.9 on 2023-05-24 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0169_additional_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='created_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
