# Generated by Django 4.1.9 on 2023-06-07 13:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0170_add_created_by_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitembatch',
            name='batch_month',
            field=models.IntegerField(default=6, verbose_name='Invoice batch month'),
        ),
        migrations.AddField(
            model_name='invoiceitembatch',
            name='batch_type',
            field=models.CharField(choices=[('CNS', 'CNS'), ('AD', 'Assurance Dépendance'), ('OTHER', 'Autre')], default='CNS', max_length=25),
        ),
        migrations.AddField(
            model_name='invoiceitembatch',
            name='batch_year',
            field=models.IntegerField(default=2023, verbose_name='Invoice batch year'),
        ),
        migrations.AddField(
            model_name='invoiceitembatch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoiceitembatch',
            name='force_generation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoiceitembatch',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitembatch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='invoiceitembatch',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Invoice batch start date'),
        ),
        migrations.AlterField(
            model_name='invoiceitembatch',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Invoice batch start date'),
        ),
        migrations.AlterField(
            model_name='simplifiedtimesheet',
            name='time_sheet_month',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], default=6),
        ),
        migrations.CreateModel(
            name='InvoiceItemBatchLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.invoiceitem')),
                ('invoice_item_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.invoiceitembatch')),
            ],
        ),
        migrations.AddField(
            model_name='invoiceitembatch',
            name='linked_items',
            field=models.ManyToManyField(related_name='linked_batches', through='invoices.InvoiceItemBatchLink', to='invoices.invoiceitem'),
        ),
    ]
