# Generated by Django 4.1.9 on 2023-06-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0171_batch_nurse_invoices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='batch',
        ),
        migrations.AlterField(
            model_name='invoiceitembatch',
            name='batch_type',
            field=models.CharField(choices=[('CNS_INF', 'CNS Infirimier'), ('CNS_PAL', 'CNS Paliatif'), ('AD', 'Assurance Dépendance'), ('OTHER', 'Autre')], default='CNS', max_length=25),
        ),
    ]
