# Generated by Django 4.1.9 on 2023-06-14 10:29

from django.db import migrations, models
import invoices.actions.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0171_batch_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitembatch',
            name='batch_type',
            field=models.CharField(choices=[('CNS_INF', 'CNS Infirimier'), ('CNS_PAL', 'CNS Paliatif'), ('AD', 'Assurance Dépendance'), ('OTHER', 'Autre')], default='CNS_INF', max_length=50),
        ),
        migrations.AddField(
            model_name='invoiceitembatch',
            name='medical_prescription_files',
            field=models.FileField(blank=True, null=True, upload_to=invoices.actions.helpers.invoice_itembatch_medical_prescription_filename),
        ),
        migrations.AddField(
            model_name='invoiceitembatch',
            name='prefac_file',
            field=models.FileField(blank=True, null=True, upload_to=invoices.actions.helpers.invoice_itembatch_prefac_filename),
        ),
    ]
