# Generated by Django 4.1.9 on 2023-06-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0173_batch_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='carecode',
            name='is_package',
            field=models.BooleanField(default=False, help_text='Si vous sélectionnez cette option, cela signifie que cette prestation est un forfait et que le prix est fixe', verbose_name='Forfait'),
        ),
        migrations.AlterField(
            model_name='invoiceitembatch',
            name='end_date',
            field=models.DateField(verbose_name='Invoice batch end date'),
        ),
    ]
