# Generated by Django 4.1.9 on 2023-07-05 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0174_care_code_package_ftr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitembatch',
            name='batch_type',
            field=models.CharField(choices=[('CNS_INF', 'CNS Infirimier'), ('CNS_INF_PACK', 'Forfait Infirimier'), ('CNS_PAL', 'CNS Paliatif'), ('AD', 'Assurance Dépendance'), ('OTHER', 'Autre')], default='CNS_INF', max_length=50),
        ),
        migrations.AlterField(
            model_name='simplifiedtimesheet',
            name='time_sheet_month',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], default=7),
        ),
        migrations.CreateModel(
            name='AlternateAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_address', models.TextField(help_text='ex: 1 rue de la bonne santé, L-1214 Luxembourg', max_length=255, verbose_name='Adresse complète')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='invoices.patient')),
            ],
        ),
    ]
