# Generated by Django 4.1.9 on 2023-07-10 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoices', '0176_alternate_addr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_alert', models.CharField(max_length=255, verbose_name='Text alert')),
                ('alert_level', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('DANGER', 'Danger')], max_length=20, verbose_name='Alert level')),
                ('date_alert', models.DateTimeField(auto_now_add=True, verbose_name='Date Alert')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is Read')),
                ('date_read', models.DateTimeField(blank=True, null=True, verbose_name='Date Read')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('link_to_object', models.URLField(blank=True, max_length=255, null=True)),
                ('link_to_object_name', models.CharField(blank=True, max_length=255, null=True)),
                ('link_to_object_id', models.IntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, max_length=255, null=True, verbose_name='Comment')),
                ('alert_created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_created_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
