# Generated by Django 4.1.10 on 2023-07-17 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0177_alert_mgmt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ['-date_alert'], 'verbose_name': 'Alert', 'verbose_name_plural': 'Alerts'},
        ),
    ]
