# Generated by Django 4.1.11 on 2023-09-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0179_google_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalprescription',
            name='notes',
            field=models.TextField(blank=True, help_text='Veuillez suivre la nomenclature suivante: Pathologies: ...; Antécédents: ...; Traitements: ...; Allergies: ...; Autres: ...', max_length=1000, null=True, verbose_name='Notes ou remarques'),
        ),
        migrations.AlterField(
            model_name='simplifiedtimesheet',
            name='time_sheet_month',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], default=9),
        ),
    ]
