# Generated by Django 4.1.11 on 2023-09-20 09:50

from django.db import migrations, models
import django.db.models.deletion
import invoices.actions.helpers
import invoices.storages


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0180_cleanup_regulier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bedsore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification_date', models.DateField()),
                ('location', models.CharField(help_text='Exemple: Dos, Talon droit, etc.', max_length=255)),
                ('initial_description', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.patient')),
            ],
        ),
        migrations.CreateModel(
            name='BedsoreEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_date', models.DateField()),
                ('stage', models.IntegerField(choices=[(1, 'Stage 1'), (2, 'Stage 2'), (3, 'Stage 3'), (4, 'Stage 4')])),
                ('size', models.DecimalField(decimal_places=2, max_digits=5)),
                ('depth', models.DecimalField(decimal_places=2, max_digits=5)),
                ('treatment', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(storage=invoices.storages.CustomizedGoogleDriveStorage(), upload_to=invoices.actions.helpers.update_bedsore_pictures_filenames)),
                ('bedsore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.bedsore')),
            ],
        ),
    ]
