# Generated by Django 4.1.11 on 2023-09-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0181_bedsore_ftr'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bedsore',
            options={'ordering': ['-identification_date'], 'verbose_name': 'Escarre', 'verbose_name_plural': 'Escarres'},
        ),
        migrations.AlterModelOptions(
            name='bedsoreevaluation',
            options={'verbose_name': 'Evaluation', 'verbose_name_plural': 'Evaluations'},
        ),
        migrations.AddField(
            model_name='bedsore',
            name='is_linked_to_care',
            field=models.BooleanField(default=True, help_text="Si vous sélectionnez cette option, cela signifie que l'escarre est liée à la prise en charge"),
        ),
    ]
