# Generated by Django 4.1.11 on 2023-09-21 12:13

from django.db import migrations, models
import invoices.actions.helpers
import invoices.models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0182_bedsore_ftr'),
    ]

    operations = [
        migrations.AddField(
            model_name='bedsoreevaluation',
            name='bedsore_evolution',
            field=models.CharField(choices=[('NA', 'Première visite'), ('BETTER', 'Amélioration'), ('STABLE', 'Stable'), ('WORSE', 'Dégradation')], default='NA', max_length=8),
        ),
        migrations.AlterField(
            model_name='bedsoreevaluation',
            name='depth',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Profondeur en cm'),
        ),
        migrations.AlterField(
            model_name='bedsoreevaluation',
            name='image',
            field=models.ImageField(upload_to=invoices.actions.helpers.update_bedsore_pictures_filenames, validators=[invoices.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='bedsoreevaluation',
            name='size',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Taille en cm'),
        ),
    ]
