# Generated by Django 4.1.11 on 2023-09-21 14:07

from django.db import migrations, models
import django.db.models.deletion
import invoices.actions.helpers
import invoices.models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0183_bedsore_ftr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedsoreevaluation',
            name='image',
            field=models.ImageField(upload_to=invoices.actions.helpers.update_bedsore_pictures_filenames, validators=[invoices.models.validate_image]),
        ),
        migrations.CreateModel(
            name='BedsoreRiskAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_date', models.DateField()),
                ('sensory_perception', models.IntegerField(choices=[(1, 'Complètement limitée'), (2, 'Très limitée'), (3, 'Légèrement limitée'), (4, 'Pas de limitation')])),
                ('moisture', models.IntegerField(choices=[(1, 'Constamment humide'), (2, 'Très humide'), (3, 'Occasionnellement humide'), (4, 'Rarement humide')])),
                ('activity', models.IntegerField(choices=[(1, 'Alité'), (2, 'Fauteuil'), (3, 'Marche occasionnellement'), (4, 'Marche fréquemment')])),
                ('mobility', models.IntegerField(choices=[(1, 'Complètement immobile'), (2, 'Très limitée'), (3, 'Légèrement limitée'), (4, 'Pas de limitation')])),
                ('nutrition', models.IntegerField(choices=[(1, 'Très mauvaise'), (2, 'Probablement inadéquate'), (3, 'Adéquate'), (4, 'Excellente')])),
                ('friction_shear', models.IntegerField(choices=[(1, 'Problème significatif'), (2, 'Problème potentiel'), (3, 'Pas de problème apparent')])),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.patient')),
            ],
        ),
    ]
