# Generated by Django 4.1.11 on 2023-09-21 14:09

from django.db import migrations, models
import invoices.actions.helpers
import invoices.models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0184_bedsore_risk_ftr'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bedsoreriskassessment',
            options={'ordering': ['-assessment_date'], 'verbose_name': 'Évaluation du risque de développer une escarre', 'verbose_name_plural': 'Évaluations du risque de développer une escarre'},
        ),
        migrations.AlterField(
            model_name='bedsoreevaluation',
            name='image',
            field=models.ImageField(upload_to=invoices.actions.helpers.update_bedsore_pictures_filenames, validators=[invoices.models.validate_image]),
        ),
    ]
