# Generated by Django 4.2.5 on 2023-10-02 18:50

import colorfield.fields
from django.db import migrations, models
import invoices.actions.helpers
import invoices.models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0188_remove_link_to_detail_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalprescription',
            name='file',
        ),
        migrations.AlterField(
            model_name='bedsoreevaluation',
            name='image',
            field=models.ImageField(upload_to=invoices.actions.helpers.update_bedsore_pictures_filenames, validators=[invoices.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='color_cell',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='employee',
            name='color_text',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None),
        ),
    ]
