# Generated by Django 4.2.6 on 2023-10-17 08:30

from django.db import migrations, models
import django.db.models.deletion
import invoices.actions.helpers
import invoices.models
import invoices.resources


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0193_sending_date_per_generated_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedsoreevaluation',
            name='image',
            field=models.ImageField(upload_to=invoices.actions.helpers.update_bedsore_pictures_filenames, validators=[invoices.models.validate_image]),
        ),
        migrations.CreateModel(
            name='MaintenanceFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_date', models.DateField()),
                ('description', models.CharField(max_length=50)),
                ('mileage', models.IntegerField(blank=True, null=True)),
                ('file', models.FileField(upload_to=invoices.resources.maintenance_file_storage_location)),
                ('car_link', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.car')),
            ],
            options={
                'ordering': ['-file_date'],
            },
        ),
    ]
