# Generated by Django 3.2 on 2021-04-28 13:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0104_patient_bio'),
        ('dependence', '0001_move_anamnesis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientanamnesis',
            name='dressing_habits',
        ),
        migrations.RemoveField(
            model_name='patientanamnesis',
            name='family_ties',
        ),
        migrations.RemoveField(
            model_name='patientanamnesis',
            name='friend_ties',
        ),
        migrations.RemoveField(
            model_name='patientanamnesis',
            name='general_wishes',
        ),
        migrations.RemoveField(
            model_name='patientanamnesis',
            name='important_persons_ties',
        ),
        migrations.RemoveField(
            model_name='patientanamnesis',
            name='occupation_habits',
        ),
        migrations.RemoveField(
            model_name='patientanamnesis',
            name='preferred_drinks',
        ),
        migrations.RemoveField(
            model_name='patientanamnesis',
            name='shower_habits',
        ),
        migrations.AddField(
            model_name='patientanamnesis',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date création'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientanamnesis',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour'),
        ),
        migrations.AlterField(
            model_name='assignedphysician',
            name='anamnesis',
            field=models.ForeignKey(blank=True, default=None, help_text='Please enter hospitalization dates of the patient', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dep_patient_anamnesis', to='dependence.patientanamnesis'),
        ),
        migrations.AlterField(
            model_name='assignedphysician',
            name='assigned_physician',
            field=models.ForeignKey(blank=True, default=None, help_text='Please enter physician of the patient', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dep_assigned_physicians', to='invoices.physician', verbose_name='Médecin'),
        ),
        migrations.AlterField(
            model_name='biographyhabits',
            name='biography',
            field=models.ForeignKey(blank=True, default=None, help_text='Veuillez saisir les habitudes du bénéficiaire', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dep_habit_patient_biography', to='dependence.patientanamnesis'),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='patient_anamnesis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dep_contactpers_to_anamnesis', to='dependence.patientanamnesis'),
        ),
        migrations.AlterField(
            model_name='dependenceinsurance',
            name='dep_anamnesis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dep_dep_ins_to_anamnesis', to='dependence.patientanamnesis'),
        ),
        migrations.AlterField(
            model_name='otherstakeholder',
            name='stakeholder_anamnesis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dep_stakeholder_to_anamnesis', to='dependence.patientanamnesis'),
        ),
        migrations.AlterField(
            model_name='patientanamnesis',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dep_anamnesis_to_patient', to='invoices.patient'),
        ),
        migrations.CreateModel(
            name='SocialHabits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habit_type', models.CharField(blank=True, choices=[('FML', 'Famille'), ('FRND', 'Friends'), ('IMP', 'Personnes importantes')], default=None, max_length=4, null=True, verbose_name='Type')),
                ('habit_description', models.TextField(blank=True, default=None, help_text='Veuillez décrire les habitudes sociales', max_length=200, null=True, verbose_name='Description')),
                ('biography', models.ForeignKey(blank=True, default=None, help_text='Veuillez saisir les habitudes du bénéficiaire', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='social_habit_patient_biography', to='dependence.patientanamnesis')),
            ],
            options={
                'verbose_name': 'Habitude Sociale',
                'verbose_name_plural': 'Habitudes Sociales',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ActivityHabits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habit_type', models.CharField(blank=True, choices=[('WASH', 'Se soigner'), ('DRESS', 'Habillements'), ('OCCUP', 'Occupations'), ('DSRS', 'Souhaits')], default=None, max_length=5, null=True, verbose_name='Type')),
                ('habit_description', models.TextField(blank=True, default=None, help_text='Veuillez décrire les habitudes en fonction du type', max_length=200, null=True, verbose_name='Description')),
                ('biography', models.ForeignKey(blank=True, default=None, help_text='Veuillez saisir les habitudes du bénéficiaire', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activity_habit_patient_biography', to='dependence.patientanamnesis')),
            ],
            options={
                'verbose_name': "Habitude d'Activités",
                'verbose_name_plural': "Habitudes d'Activités",
                'ordering': ['-id'],
            },
        ),
    ]
