# Generated by Django 4.2.7 on 2023-12-01 15:58

import dependence.activity
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependence', '0001_initial_after_major_november_cleanup'),
    ]

    operations = [
        migrations.AddField(
            model_name='longtermmonthlyactivityfile',
            name='return_file',
            field=models.FileField(blank=True, null=True, upload_to=dependence.activity.long_term_care_activity_return_declaration_file_path, verbose_name='Return File'),
        ),
        migrations.AlterField(
            model_name='monthlyparameters',
            name='params_month',
            field=models.IntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], default=12),
        ),
    ]
