# Generated by Django 3.2 on 2021-04-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependence', '0002_move_habits_to_inlines'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientanamnesis',
            name='preferred_drinks',
            field=models.TextField(blank=True, default=None, max_length=250, null=True, verbose_name='Boissons préfèrées'),
        ),
    ]
