# Generated by Django 4.2.8 on 2023-12-21 15:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0011_contractor_ftr_informal_caregiver'),
        ('dependence', '0002_create_return_file_for_declaration'),
    ]

    operations = [
        migrations.AddField(
            model_name='longtermcareinvoiceitem',
            name='subcontractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='long_term_invoice_items', to='invoices.subcontractor'),
        ),
        migrations.AddField(
            model_name='longtermcareinvoiceline',
            name='subcontractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='long_term_invoice_lines', to='invoices.subcontractor'),
        ),
        migrations.CreateModel(
            name='InformalCaregiverUnavailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unavailability_date', models.DateField(default=django.utils.timezone.now, verbose_name='Unavailable date')),
                ('unavailability_type', models.CharField(choices=[('DEBUT', 'Start'), ('RETOUR', 'Return'), ('CORRECTION', 'Correction'), ('DEFINITIVE', 'Definitive')], max_length=10, verbose_name='Unavailable type')),
                ('unavailability_reference', models.CharField(help_text='Le prestataire est libre de choisir son système de référencement des déclarations', max_length=50, verbose_name='Unavailable reference')),
                ('cns_code_of_the_informal_caregiver', models.CharField(help_text='Code CNS de l’aidant. Ce champ est obligatoire.', max_length=50, verbose_name='CNS code of the informal caregiver')),
                ('link_unav_to_chg_dec_file', models.ForeignKey(help_text='Link to the file containing the declaration of change', on_delete=django.db.models.deletion.CASCADE, related_name='informalcaregiverunavailability_to_chg_dec_file', to='dependence.changedeclarationfile')),
                ('patient', models.ForeignKey(help_text='Only looks for patients covered by long-term care insurance, check that the checkbox is validated if you cannot find your patient', limit_choices_to={'is_under_dependence_insurance': True}, on_delete=django.db.models.deletion.CASCADE, related_name='informalcaregiverunavailability_to_patient', to='invoices.patient')),
            ],
            options={
                'verbose_name': 'Indisponibilité aidant',
                'verbose_name_plural': 'Indisponibilités aidant',
            },
        ),
    ]
