# Generated by Django 4.2.8 on 2023-12-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependence', '0004_contractor_ftr_informal_caregiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='longtermcareinvoiceitem',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='longtermcareinvoiceitem',
            name='refused_by_insurance',
            field=models.BooleanField(default=False, verbose_name='Refused by insurance'),
        ),
    ]
