# Generated by Django 3.2.7 on 2021-09-20 16:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoices', '0107_add_patient_parameters'),
        ('dependence', '0004_holiday_request_refine_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('params_year', models.PositiveIntegerField(default=2021)),
                ('params_month', models.IntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], default=9)),
                ('weight', models.PositiveSmallIntegerField(verbose_name='Poids (KG)')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='health_params_to_patient', to='invoices.patient')),
            ],
            options={
                'verbose_name': 'Paramètre Patient',
                'verbose_name_plural': 'Paramètres Patient',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TensionAndTemperatureParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('params_date_time', models.DateTimeField(default=datetime.datetime.now)),
                ('systolic_blood_press', models.PositiveSmallIntegerField(default=0, verbose_name='tension min.')),
                ('diastolic_blood_press', models.PositiveSmallIntegerField(default=0, verbose_name='tension max.')),
                ('temperature', models.PositiveSmallIntegerField(default=0)),
                ('stools', models.PositiveSmallIntegerField(choices=[(0, '-'), (1, '+'), (2, '++'), (3, '+++')], default=0, verbose_name='Selles')),
                ('weight', models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='Poids (KG)')),
                ('general_remarks', models.TextField(blank=True, default=None, max_length=25, null=True, verbose_name='Remarques générales')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('monthly_params', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='health_params_to_monthly_params', to='dependence.monthlyparameters')),
                ('user', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
