# Generated by Django 4.2.8 on 2024-01-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependence', '0005_add_flags_on_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='longtermcareinvoiceitem',
            name='quantity',
            field=models.FloatField(default=1, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='monthlyparameters',
            name='params_month',
            field=models.IntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], default=1),
        ),
        migrations.AlterField(
            model_name='monthlyparameters',
            name='params_year',
            field=models.PositiveIntegerField(default=2024),
        ),
    ]
