# Generated by Django 3.2.7 on 2021-09-22 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependence', '0005_add_patient_parameters'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tensionandtemperatureparameters',
            options={'ordering': ['-id'], 'verbose_name': 'Paramètre', 'verbose_name_plural': 'Paramètres'},
        ),
        migrations.AlterField(
            model_name='tensionandtemperatureparameters',
            name='diastolic_blood_press',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Tension min.'),
        ),
        migrations.AlterField(
            model_name='tensionandtemperatureparameters',
            name='params_date_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='tensionandtemperatureparameters',
            name='systolic_blood_press',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Tension max.'),
        ),
        migrations.AlterField(
            model_name='tensionandtemperatureparameters',
            name='temperature',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='tensionandtemperatureparameters',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=4, null=True, verbose_name='Poids (KG)'),
        ),
    ]
