# Generated by Django 4.2.8 on 2024-01-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependence', '0006_float_instead_of_int'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalcaresummaryperpatientdetail',
            name='custom_description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sharedmedicalcaresummaryperpatientdetail',
            name='custom_description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
