# Generated by Django 3.2.7 on 2021-09-22 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependence', '0006_enrich_params'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyparameters',
            name='weight',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Poids (KG)'),
        ),
    ]
