# Generated by Django 4.2.8 on 2024-02-02 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependence', '0007_enlarge_custom_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyparameters',
            name='params_month',
            field=models.IntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], default=2),
        ),
    ]
