# Generated by Django 3.2.7 on 2021-09-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependence', '0007_enrich_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='tensionandtemperatureparameters',
            name='oximeter_saturation',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='Saturation O2 %'),
        ),
    ]
