# Generated by Django 3.2.8 on 2021-10-13 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0110_additional_employees'),
        ('dependence', '0008_enrich_params'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyparameters',
            name='params_month',
            field=models.IntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], default=10),
        ),
        migrations.CreateModel(
            name='CarePlanMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_number', models.PositiveSmallIntegerField(verbose_name='Num.')),
                ('replace_plan_number', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Remplce Num.')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_plan_to_patient', to='invoices.patient')),
            ],
            options={
                'verbose_name': 'Plan de Soins Détaillé',
                'verbose_name_plural': 'Plans de Soins Détaillé',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CarePlanDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('params_day_of_week', models.IntegerField(choices=[(0, 'Tous'), (1, 'Lundi'), (2, 'Mardi'), (3, 'Mercredi'), (4, 'Jeudi'), (5, 'Vendredi'), (6, 'Samedi'), (7, 'Dimanche')], verbose_name='Jour')),
                ('time_start', models.TimeField(verbose_name='De')),
                ('time_end', models.TimeField(verbose_name='A')),
                ('care_actions', models.TextField(max_length=500, verbose_name='Actions à prévoir')),
                ('care_plan_to_master', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='care_plan_detail_to_master', to='dependence.careplanmaster')),
            ],
            options={
                'verbose_name': 'Détail',
                'verbose_name_plural': 'Détails',
                'ordering': ['-id'],
            },
        ),
    ]
