# Generated by Django 4.2.10 on 2024-03-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependence', '0009_aai_enrichment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aaitransmission',
            old_name='aai_month_month',
            new_name='aai_month',
        ),
        migrations.AlterField(
            model_name='aaitransdetail',
            name='session_duration',
            field=models.DurationField(blank=True, default=None, help_text='Durée de la séance sous format HH:MM:SS', null=True, verbose_name='Durée'),
        ),
    ]
