# Generated by Django 4.2.10 on 2024-03-05 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0031_agreement_fusion'),
        ('dependence', '0010_aai_enrichment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aaitransdetail',
            name='means_paraph',
            field=models.ForeignKey(blank=True, default=None, limit_choices_to=models.Q(('user__groups__name', 'ergo-kine')), null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_of_means', to='invoices.employee', verbose_name='Paraphe'),
        ),
    ]
