# Generated by Django 3.2.8 on 2021-10-15 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

import invoices


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dependence', '0010_careplan_detail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='careplandetail',
            options={'ordering': ['id'], 'verbose_name': 'Détail', 'verbose_name_plural': 'Détails'},
        ),
        migrations.AddField(
            model_name='careplanmaster',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date création'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='careplanmaster',
            name='last_valid_plan',
            field=models.BooleanField(default=False, verbose_name='Dernier plan valide'),
        ),
        migrations.AddField(
            model_name='careplanmaster',
            name='plan_decision_date',
            field=models.DateField(blank=True, help_text="Date de la décision de l'assurance dépendance", null=True, verbose_name='Date décision:'),
        ),
        migrations.AddField(
            model_name='careplanmaster',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour'),
        ),
        migrations.AddField(
            model_name='careplanmaster',
            name='user',
            field=invoices.db.fields.CurrentUserField(default=invoices.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='careplanmaster',
            name='plan_start_date',
            field=models.DateField(default=django.utils.timezone.now, help_text="Date du début d'application du plan des soins", verbose_name='À partir de:'),
        ),
    ]
