# Generated by Django 4.2.11 on 2024-03-14 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0034_aai_changes'),
        ('dependence', '0011_agreement_fusion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aaitransdetail',
            name='objectives',
        ),
        migrations.AlterField(
            model_name='aaitransdetail',
            name='means',
            field=models.TextField(blank=True, default=None, max_length=200, null=True, verbose_name='Moyens/Actions'),
        ),
        migrations.AlterField(
            model_name='aaitransdetail',
            name='results',
            field=models.TextField(blank=True, default=None, max_length=200, null=True, verbose_name='Résultats'),
        ),
        migrations.CreateModel(
            name='AAIObjective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective', models.CharField(max_length=100, verbose_name='Objectif')),
                ('description', models.TextField(max_length=1000, verbose_name='Description')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('patient', models.ForeignKey(limit_choices_to={'is_under_dependence_insurance': True}, on_delete=django.db.models.deletion.CASCADE, related_name='aai_objective_to_patient', to='invoices.patient')),
            ],
            options={
                'verbose_name': 'Objectif AAI',
                'verbose_name_plural': 'Objectifs AAI',
                'ordering': ['objective'],
            },
        ),
        migrations.AddField(
            model_name='aaitransdetail',
            name='link_to_objectives',
            field=models.ManyToManyField(to='dependence.aaiobjective', verbose_name='Lien avec objectifs'),
        ),
    ]
