# Generated by Django 3.2.8 on 2021-10-26 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dependence', '0012_careplan_adds'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareOccurrence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str_name', models.CharField(max_length=50, verbose_name='Nom')),
            ],
        ),
        migrations.AddField(
            model_name='careplandetail',
            name='params_occurrence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dependence.careoccurrence', verbose_name='Occurence'),
        ),
    ]
