# Generated by Django 3.2.8 on 2021-10-26 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependence', '0013_migrating_occurrence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careplandetail',
            name='params_occurrence',
        ),
        migrations.AddField(
            model_name='careplandetail',
            name='params_occurrence',
            field=models.ManyToManyField(blank=True, null=True, to='dependence.CareOccurrence', verbose_name='Occurence'),
        ),
    ]
