# Generated by Django 4.2.11 on 2024-03-15 19:52

import dependence.aai
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependence', '0013_aai_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='longtermcareinvoiceitem',
            name='xml_invoice_reference',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Référence de facturation'),
        ),
        migrations.AddField(
            model_name='longtermcareinvoiceline',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='longtermcareinvoiceline',
            name='refused_by_insurance',
            field=models.BooleanField(default=False, verbose_name='Refused by insurance'),
        ),
        migrations.AddField(
            model_name='longtermcareinvoiceline',
            name='xml_invoice_reference',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Référence de facturation'),
        ),
        migrations.AlterField(
            model_name='aaiobjectivefiles',
            name='file',
            field=models.FileField(upload_to=dependence.aai.aai_objective_files, verbose_name='Fichier'),
        ),
        migrations.AlterField(
            model_name='longtermcareinvoiceitem',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Comment'),
        ),
    ]
