# Generated by Django 3.2.9 on 2021-11-11 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0111_add_dep_insurance_flag'),
        ('dependence', '0014_migrating_occurrence'),
    ]

    operations = [
        migrations.AddField(
            model_name='tensionandtemperatureparameters',
            name='heart_pulse',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Pouls'),
        ),
        migrations.AlterField(
            model_name='careplandetail',
            name='params_occurrence',
            field=models.ManyToManyField(to='dependence.CareOccurrence', verbose_name='Occurence'),
        ),
        migrations.AlterField(
            model_name='careplanmaster',
            name='patient',
            field=models.ForeignKey(help_text="Ne recheche que les patients pris en charge par l'assurance dépendance, vérifiez que la checkbox est validé si vous ne trouvez pas votre patient", limit_choices_to={'is_under_dependence_insurance': True}, on_delete=django.db.models.deletion.CASCADE, related_name='care_plan_to_patient', to='invoices.patient'),
        ),
        migrations.AlterField(
            model_name='monthlyparameters',
            name='params_month',
            field=models.IntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], default=11),
        ),
    ]
