# Generated by Django 4.0.4 on 2022-06-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependence', '0017_remove_day_field_from_care_plan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlyparameters',
            options={'ordering': ['-id'], 'verbose_name': 'Surveillance Paramètres', 'verbose_name_plural': 'Surveillances Param.'},
        ),
        migrations.AddField(
            model_name='tensionandtemperatureparameters',
            name='blood_glucose',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Mesure de la glycémie'),
        ),
        migrations.AlterField(
            model_name='monthlyparameters',
            name='params_month',
            field=models.IntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], default=6),
        ),
        migrations.AlterField(
            model_name='tensionandtemperatureparameters',
            name='heart_pulse',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='Pouls'),
        ),
    ]
