# Generated by Django 4.0.4 on 2022-06-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependence', '0018_add_params'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tensionandtemperatureparameters',
            name='blood_glucose',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=4, null=True, verbose_name='Mesure de la glycémie'),
        ),
        migrations.AlterField(
            model_name='tensionandtemperatureparameters',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3, null=True),
        ),
    ]
