# Generated by Django 4.0.5 on 2022-06-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependence', '0019_no_mandatory_params'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tensionandtemperatureparameters',
            options={'ordering': ['params_date_time'], 'verbose_name': 'Paramètre', 'verbose_name_plural': 'Paramètres'},
        ),
        migrations.AlterField(
            model_name='tensionandtemperatureparameters',
            name='stools',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '-'), (1, '+'), (2, '++'), (3, '+++')], default=None, null=True, verbose_name='Selles'),
        ),
        migrations.AlterField(
            model_name='tensionandtemperatureparameters',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3, null=True, verbose_name='Température'),
        ),
    ]
