# Generated by Django 4.2.11 on 2024-05-16 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dependence', '0019_batch_12_pct'),
    ]

    operations = [
        migrations.AddField(
            model_name='longtermcareinvoicefile',
            name='invoice_sequence_number',
            field=models.PositiveIntegerField(default=1, verbose_name='Invoice Sequence Number'),
        ),
        migrations.AddField(
            model_name='longtermcareinvoicefile',
            name='long_term_invoice_file_that_corrects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dependence.longtermcareinvoicefile'),
        ),
    ]
