# Generated by Django 4.0.5 on 2022-06-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0118_enrich_careplan_1'),
        ('dependence', '0020_cleanup'),
    ]

    operations = [
        migrations.AddField(
            model_name='careplandetail',
            name='req_skills',
            field=models.ManyToManyField(related_name='care_job_position', to='invoices.jobposition', verbose_name='Qualif.'),
        ),
        migrations.AddField(
            model_name='careplandetail',
            name='required_technical_resources',
            field=models.TextField(blank=True, default=None, max_length=500, null=True, verbose_name='Ressources techniques requises'),
        ),
        migrations.AlterField(
            model_name='careplandetail',
            name='params_occurrence',
            field=models.ManyToManyField(related_name='from_careplan_detail_to_occurence+', to='dependence.careoccurrence', verbose_name='Occurence'),
        ),
    ]
