# Generated by Django 4.2.11 on 2024-06-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependence', '0021_migrate_latitudes'),
    ]

    operations = [
        migrations.AddField(
            model_name='longtermcareinvoicefile',
            name='invoice_to_be_sent_to_CNS',
            field=models.BooleanField(default=True, verbose_name='Invoice to be sent to CNS'),
        ),
    ]
