# Generated by Django 4.0.6 on 2022-07-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependence', '0022_enrich_employee_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tensionandtemperatureparameters',
            name='general_remarks',
            field=models.TextField(blank=True, default=None, max_length=200, null=True, verbose_name='Remarques générales'),
        ),
    ]
