# Generated by Django 4.2.11 on 2024-06-17 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependence', '0022_flag_to_avoid_validation_if_subcontracting_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalcaresummaryperpatientdetail',
            name='custom_description',
            field=models.TextField(blank=True, max_length=700, null=True),
        ),
    ]
