# Generated by Django 4.2.11 on 2024-07-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependence', '0023_enlarge_descriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='longtermcareinvoiceline',
            name='skip_aev_check',
            field=models.BooleanField(default=False, verbose_name='Skip AEV Check'),
        ),
        migrations.AlterField(
            model_name='aaitransmission',
            name='aai_month',
            field=models.IntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], default=7),
        ),
        migrations.AlterField(
            model_name='monthlyparameters',
            name='params_month',
            field=models.IntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], default=7),
        ),
    ]
