# Generated by Django 4.1 on 2022-08-16 16:16

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import django_currentuser.middleware
import invoices.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dependence', '0024_aai_and_mode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aaitransdetail',
            options={'ordering': ['date_time_means_set'], 'verbose_name': 'Détail', 'verbose_name_plural': 'Détails'},
        ),
        migrations.AlterField(
            model_name='aaitransmission',
            name='user',
            field=invoices.db.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
    ]
