# Generated by Django 4.2.15 on 2024-08-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependence', '0024_skip_aev_checks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aaitransmission',
            name='aai_month',
            field=models.IntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], default=8),
        ),
        migrations.AlterField(
            model_name='monthlyparameters',
            name='params_month',
            field=models.IntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], default=8),
        ),
        migrations.AlterField(
            model_name='patientanamnesis',
            name='reason_for_dependence',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Motif de prise en charge'),
        ),
    ]
