# Generated by Django 4.1.3 on 2022-12-11 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import invoices.db.fields
import invoices.middleware


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dependence", "0026_add_evs_to_params"),
    ]

    operations = [
        migrations.CreateModel(
            name="FallDeclaration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "datetimeOfFall",
                    models.DateTimeField(verbose_name="Date, heure de la chute"),
                ),
                (
                    "placeOfFall",
                    models.CharField(max_length=200, verbose_name="Lieu de la chute"),
                ),
                (
                    "witnesses",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=255,
                        null=True,
                        verbose_name="Témoins éventuels",
                    ),
                ),
                (
                    "fall_circumstance",
                    models.CharField(
                        choices=[
                            (
                                "FCI_ON_SAME_LEVEL",
                                "Chute de plain-pied résultant de glissade, faux-pas et trébuchement",
                            ),
                            ("FCI_FROM_BED", "Chute d’un lit"),
                            ("FCI_FROM_CHAIR", "Chute d’une chaise"),
                            ("FCI_FROM_STAIRS", "Chute dans un escalier et de marches"),
                            (
                                "FCI_WHILE_HELD",
                                "Chute en étant porté ou soutenu par un tiers",
                            ),
                            ("FCI_FROM_WHEELC", "Chute d’un fauteuil roulant"),
                            ("FCI_FROM_TOILET", "Chute d’un siège de toilette"),
                            ("FCI_OTHER_CAUSES", "Autre"),
                        ],
                        max_length=255,
                        verbose_name="Circonstances de la chute",
                    ),
                ),
                (
                    "other_fall_circumstance",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=255,
                        null=True,
                        verbose_name="Autre circonstances de la chute",
                    ),
                ),
                (
                    "incident_circumstance",
                    models.TextField(
                        blank=True,
                        default=None,
                        max_length=255,
                        null=True,
                        verbose_name="Circonstances de l’incident",
                    ),
                ),
                (
                    "other_fall_consequence",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=255,
                        null=True,
                        verbose_name="Autre conséquence de la chute",
                    ),
                ),
                (
                    "other_required_medical_act",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=255,
                        null=True,
                        verbose_name="Autres actes médicaux et/ou infirmiers requis dans les 24h",
                    ),
                ),
                (
                    "medications_risk_factor",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "FMRF_MEDS",
                                "Médicaments (psychotropes, anti-hypertenseurs, polypragmasie etc.)",
                            ),
                            ("FMRF_OTHER", "Autres: > 4 médicaments"),
                        ],
                        default=None,
                        max_length=255,
                        null=True,
                        verbose_name="Facteurs de risque",
                    ),
                ),
                (
                    "mobility_disability",
                    models.CharField(
                        choices=[
                            (
                                "FCMD_NONE",
                                "Se déplace seul, sans difficultés, sans moyens auxiliaires",
                            ),
                            (
                                "FMD_DIFFICULTY",
                                "Se déplace seul avec difficulté avec ou sans moyens auxiliaires",
                            ),
                            (
                                "FMD_ACCOMPANIED",
                                "Se déplace accompagné sans moyens auxiliaires",
                            ),
                            (
                                "FMD_AUXILIARY",
                                "Se déplace accompagné avec moyens auxiliaires",
                            ),
                        ],
                        max_length=255,
                        verbose_name="Incapacité concernant les déplacements",
                    ),
                ),
                (
                    "unsuitable_footwear",
                    models.BooleanField(
                        default=False, verbose_name="Chaussures inadaptées"
                    ),
                ),
                (
                    "other_contributing_factor",
                    models.TextField(
                        blank=True,
                        default=None,
                        max_length=255,
                        null=True,
                        verbose_name="Autre facteur favorisant",
                    ),
                ),
                (
                    "preventable_fall",
                    models.BooleanField(
                        verbose_name="La chute aurait pu être prévenue"
                    ),
                ),
                (
                    "physician_informed",
                    models.BooleanField(verbose_name="Le médecin a été avisé"),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date création"
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière mise à jour"
                    ),
                ),
                (
                    "declared_by",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        limit_choices_to=models.Q(
                            ("abbreviation__in", ["XXX"]), _negated=True
                        ),
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="edeclaring_employee",
                        to="invoices.employee",
                        verbose_name="Déclaré par",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        help_text="Ne recheche que les patients pris en charge par l'assurance dépendance, vérifiez que la checkbox est validé si vous ne trouvez pas votre patient",
                        limit_choices_to={"is_under_dependence_insurance": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="falldeclaration_to_patient",
                        to="invoices.patient",
                    ),
                ),
                (
                    "user",
                    invoices.db.fields.CurrentUserField(
                        default=invoices.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fall Declaration",
                "verbose_name_plural": "Fall Declaration",
                "ordering": ["patient__id"],
            },
        ),
        migrations.CreateModel(
            name="FallRequiredMedicalAct",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "required_medical_act",
                    models.CharField(
                        choices=[
                            ("FRMA_RADIO", "Investigation radiologique"),
                            ("FRMA_MINOR_SURGERY", "Petite chirurgie"),
                            ("FRMA_TRANSFER", "Transfert"),
                            ("FRMA_NURS_SUPERV", "Surveillance infirmière accrue"),
                            ("FRMA_RESTRAINT", "Contention"),
                            ("FCO_OTHER_CAUSES", "Autres mesures"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "fall_declaration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fall_required_medical_acts",
                        to="dependence.falldeclaration",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FallIncontinence",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "incontinence",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FCMD_URINARY", "Incontinence urinaire (non sondé)"),
                            ("FI_FECAL", "Incontinence des matières fécales"),
                        ],
                        default=None,
                        max_length=255,
                        null=True,
                        verbose_name="Incontinence",
                    ),
                ),
                (
                    "fall_declaration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fall_incontinences",
                        to="dependence.falldeclaration",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FallConsequence",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "consequence",
                    models.CharField(
                        choices=[
                            ("FCO_NO_TRAUMA", "Indemne de lésions traumatiques"),
                            (
                                "FCO_SUPERF_TRAUMA",
                                "Lésion(s) traumatique(s) superficielle(s) (abrasion, contusion, ecchymose, hématome)",
                            ),
                            (
                                "FCO_OPEN_WOUND",
                                "Plaie(s) ouverte(s) (coupure, lacération)",
                            ),
                            ("FCO_DISLOCATION", "Luxation, entorse, foulure"),
                            ("FCO_PAIN", "Douleurs (évaluer la douleur svp)"),
                            ("FCO_OTHER_CAUSES", "Autre"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "fall_declaration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fall_consequences",
                        to="dependence.falldeclaration",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FallCognitiveMoodDiorder",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cognitive_mood_diorder",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FCMD_DROWSINESS_ETC", "Somnolence, stupeur ou coma"),
                            ("FCMD_DESORIENT", "Désorientation, confusion"),
                            ("FCMD_AGET", "Agitation"),
                            (
                                "FCMD_OTHER",
                                "Autres altérations des fonctions cognitives",
                            ),
                        ],
                        default=None,
                        max_length=255,
                        null=True,
                        verbose_name="Troubles cognitifs et/ou de l’humeur",
                    ),
                ),
                (
                    "fall_declaration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fall_cognitive_mood_diorders",
                        to="dependence.falldeclaration",
                    ),
                ),
            ],
        ),
    ]
