# Generated by Django 4.2.15 on 2024-08-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependence', '0026_cleanup_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientanamnesis',
            name='legal_protection_regimes',
            field=models.CharField(blank=True, choices=[('TUT', 'Tutelle'), ('CUR', 'Curatelle'), ('SAV', 'Sauvegarde de justice'), ('OTH', 'Other'), ('NONE', 'None')], default=None, max_length=50, null=True, verbose_name='Régimes de protection légale'),
        ),
        migrations.AddField(
            model_name='patientanamnesis',
            name='legal_protection_regimes_doc_link',
            field=models.FileField(blank=True, default=None, null=True, upload_to='documents/legal_protection_regimes', verbose_name='Doc. régimes de protection légale'),
        ),
        migrations.AddField(
            model_name='patientanamnesis',
            name='legal_protector_name_and_contact',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Nom et contact du protecteur légal'),
        ),
        migrations.AlterField(
            model_name='patientanamnesis',
            name='informal_caregiver',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Aidant formel'),
        ),
    ]
