# Generated by Django 4.1.3 on 2022-12-03 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import invoices.db.fields
import invoices.middleware


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dependence', '0026_add_evs_to_params'),
    ]

    operations = [
        migrations.CreateModel(
            name='FallDecleration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetimeOfFall', models.DateTimeField(verbose_name='Date, heure de la chute')),
                ('placeOfFall', models.TextField(max_length=200, verbose_name='Lieu de la chute')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('patient', models.ForeignKey(help_text="Ne recheche que les patients pris en charge par l'assurance dépendance, vérifiez que la checkbox est validé si vous ne trouvez pas votre patient", limit_choices_to={'is_under_dependence_insurance': True}, on_delete=django.db.models.deletion.CASCADE, related_name='falldecleration_to_patient', to='invoices.patient')),
                ('user', invoices.db.fields.CurrentUserField(default=invoices.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Fall Decleration',
                'verbose_name_plural': 'Fall Decleration',
                'ordering': ['patient__id'],
            },
        ),
    ]
