# Generated by Django 4.1.3 on 2022-12-11 17:51

import dependence.falldecleration
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dependence", "0027_falldecleration"),
    ]

    operations = [
        migrations.AddField(
            model_name="falldecleration",
            name="file_upload",
            field=models.FileField(
                blank=True,
                help_text="Vous pouvez attacher le scan de la déclaration",
                null=True,
                upload_to=dependence.falldecleration.update_fall_decleration_filename,
                validators=[dependence.falldecleration.validate_file],
            ),
        ),
    ]
