# Generated by Django 4.1.3 on 2022-12-11 17:51

import dependence.falldeclaration
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dependence", "0027_falldeclaration"),
    ]

    operations = [
        migrations.AddField(
            model_name="falldeclaration",
            name="file_upload",
            field=models.FileField(
                blank=True,
                help_text="Vous pouvez attacher le scan de la déclaration",
                null=True,
                upload_to=dependence.falldeclaration.update_fall_declaration_filename,
                validators=[dependence.falldeclaration.validate_file],
            ),
        ),
    ]
