# Generated by Django 4.2.15 on 2024-08-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependence', '0029_add_contact_person_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientanamnesis',
            name='hygiene_general_remarks',
            field=models.TextField(blank=True, default=None, max_length=250, null=True, verbose_name='Remarques générales'),
        ),
    ]
