# Generated by Django 4.1.6 on 2023-02-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependence', '0030_add_do_not_notify_check_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientanamnesis',
            name='anticipated_directives',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Directives anticipées'),
        ),
        migrations.AddField(
            model_name='patientanamnesis',
            name='anticipated_directives_doc_link',
            field=models.FileField(blank=True, default=None, null=True, upload_to='documents/anticipated_directives', verbose_name='Doc. directives anticipées'),
        ),
        migrations.AddField(
            model_name='patientanamnesis',
            name='domestic_animals',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Animaux domestiques'),
        ),
        migrations.AddField(
            model_name='patientanamnesis',
            name='elevator',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Ascenseur'),
        ),
        migrations.AddField(
            model_name='patientanamnesis',
            name='help_for_cleaning',
            field=models.CharField(blank=True, choices=[('FML', 'Family'), ('NTWRK', 'Network'), ('TRD', 'Third party')], default=None, max_length=10, null=True, verbose_name='Aide pour le ménage'),
        ),
        migrations.AddField(
            model_name='patientanamnesis',
            name='plan_of_share',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Plan de partage'),
        ),
        migrations.AddField(
            model_name='patientanamnesis',
            name='reason_for_dependence',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Motif de prise en charge'),
        ),
        migrations.AddField(
            model_name='patientanamnesis',
            name='religious_beliefs',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Religion'),
        ),
        migrations.AddField(
            model_name='patientanamnesis',
            name='technical_help',
            field=models.TextField(blank=True, default=None, max_length=500, null=True, verbose_name='Aides techniques'),
        ),
        migrations.AddField(
            model_name='patientanamnesis',
            name='treatments',
            field=models.TextField(blank=True, default=None, max_length=500, null=True, verbose_name='Traitements'),
        ),
        migrations.AlterField(
            model_name='monthlyparameters',
            name='params_month',
            field=models.IntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], default=2),
        ),
        migrations.AlterField(
            model_name='patientanamnesis',
            name='civil_status',
            field=models.CharField(blank=True, choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('WIDOW', 'Widow'), ('PACS', 'Pacs'), ('DIV', 'Divorced'), ('SEP', 'Separated'), ('OTH', 'Other')], default=None, max_length=7, null=True, verbose_name='État civil'),
        ),
        migrations.AlterField(
            model_name='patientanamnesis',
            name='day_care_center_activities',
            field=models.TextField(blank=True, default=None, max_length=500, null=True, verbose_name='Activités'),
        ),
        migrations.AlterField(
            model_name='patientanamnesis',
            name='mobilization',
            field=models.CharField(blank=True, choices=[('AUTNM', 'Autonomous'), ('TCNQ', 'With technical help'), ('TRD', 'With third party'), ('BD', 'Bedridden'), ('TCNQ_TRD', 'Both Technical help and third party')], default=None, max_length=15, null=True, verbose_name='Mobilisation'),
        ),
        migrations.AlterField(
            model_name='patientanamnesis',
            name='remote_alarm',
            field=models.CharField(blank=True, choices=[('RK', 'Roude Knap'), ('SDHM', 'Secher Doheem'), ('HLP', 'Help'), ('OTH', 'Other')], default=None, max_length=4, null=True, verbose_name='Alarme'),
        ),
    ]
