# Generated by Django 4.1.7 on 2023-03-01 22:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0150_create_longterm_care'),
        ('dependence', '0032_create_longterm_care'),
    ]

    operations = [
        migrations.CreateModel(
            name='LongTermCare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.ForeignKey(help_text='Only looks for patients covered by long-term care insurance, check that the checkbox is validated if you cannot find your patient', limit_choices_to={'is_under_dependence_insurance': True}, on_delete=django.db.models.deletion.CASCADE, related_name='longtermcare_to_patient', to='invoices.patient')),
            ],
            options={
                'verbose_name': 'Long term care',
                'verbose_name_plural': 'Long term cares',
                'ordering': ['patient__id'],
            },
        ),
        migrations.CreateModel(
            name='LongTermCareDeclaration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_date_of_sending', models.DateField(default=django.utils.timezone.now, verbose_name='Provider date of sending')),
                ('change_type', models.CharField(choices=[('ENTRY', 'Entry'), ('EXIT', 'Exit'), ('CORRECTION', 'Correction')], max_length=10, verbose_name='Change type')),
                ('change_reference', models.CharField(help_text='Le prestataire est libre de choisir son système de référencement des déclarations', max_length=50, verbose_name='Change reference')),
                ('change_organism_identifier', models.CharField(help_text='Correspond à la référence donnée à la déclaration par l’organisme gestionnaire. Celui-ci sera renseigné dans le fichier retour. Ce champ doit obligatoirement être renseigné lors d’une déclaration de correction.', max_length=50, verbose_name='Change organism identifier')),
                ('change_date', models.DateField(default=django.utils.timezone.now, help_text='Date d’entrée ou de sortie indiquant le jour, le mois et l’année.', verbose_name='Change date')),
                ('information', models.TextField(help_text='Ce champ est optionnel et peut contenir du texte libre.', max_length=100, verbose_name='Information')),
                ('generated_xml', models.FileField(blank=True, null=True, upload_to='long_term_care_declaration', verbose_name='Generated XML')),
                ('generated_xml_version', models.IntegerField(default=0, verbose_name='Generated XML version')),
                ('link_to_long_term_care', models.ForeignKey(help_text='Link to the long term care', on_delete=django.db.models.deletion.CASCADE, related_name='longtermcaredeclaration_to_longtermcare', to='dependence.longtermcare')),
            ],
        ),
    ]
