# Generated by Django 4.1.7 on 2023-03-02 19:48

import dependence.dependanceinsurance
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dependence', '0034_yearandmoth_mandatory_for_filename_calculation'),
    ]

    operations = [
        migrations.AddField(
            model_name='longtermcare',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date création'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='longtermcare',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour'),
        ),
        migrations.AlterField(
            model_name='longtermcaredeclaration',
            name='generated_xml',
            field=models.FileField(blank=True, null=True, upload_to=dependence.dependanceinsurance.long_term_care_declaration_file_path, verbose_name='Generated XML'),
        ),
        migrations.AlterField(
            model_name='longtermcaredeclaration',
            name='month_of_count',
            field=models.IntegerField(verbose_name='Month of count'),
        ),
        migrations.AlterField(
            model_name='longtermcaredeclaration',
            name='provider_date_of_sending',
            field=models.DateField(verbose_name='Provider date of sending'),
        ),
        migrations.AlterField(
            model_name='longtermcaredeclaration',
            name='year_of_count',
            field=models.IntegerField(verbose_name='Year of count'),
        ),
    ]
