# Generated by Django 4.1.7 on 2023-03-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependence', '0035_some_cleanup_and_tech_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='longtermcaredeclaration',
            name='change_organism_identifier',
            field=models.CharField(blank=True, help_text='Correspond à la référence donnée à la déclaration par l’organisme gestionnaire. Celui-ci sera renseigné dans le fichier retour. Ce champ doit obligatoirement être renseigné lors d’une déclaration de correction.', max_length=50, null=True, verbose_name='Change organism identifier'),
        ),
    ]
