# Generated by Django 4.1.7 on 2023-03-02 20:13

import dependence.dependanceinsurance
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependence', '0036_some_cleanup_and_tech_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='longtermcaredeclaration',
            name='generated_return_xml',
            field=models.FileField(blank=True, null=True, upload_to=dependence.dependanceinsurance.long_term_care_declaration_file_path_for_return, verbose_name='Retour CNS return XML'),
        ),
    ]
