# Generated by Django 4.1.7 on 2023-03-02 22:02

import dependence.cnscommunications
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0151_some_cleanup_and_tech_fields'),
        ('dependence', '0037_some_cleanup_and_tech_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeDeclarationFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_date_of_sending', models.DateField(verbose_name='Provider date of sending')),
                ('generated_xml', models.FileField(blank=True, null=True, upload_to=dependence.cnscommunications.long_term_care_declaration_file_path, verbose_name='Generated XML')),
                ('manually_generated_xml', models.FileField(blank=True, null=True, upload_to=dependence.cnscommunications.long_term_care_declaration_file_path, verbose_name='Manually generated XML')),
                ('generated_xml_version', models.IntegerField(default=0, verbose_name='Generated XML version')),
                ('generated_return_xml', models.FileField(blank=True, null=True, upload_to=dependence.cnscommunications.long_term_care_declaration_file_path_for_return, verbose_name='Retour CNS return XML')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
            ],
            options={
                'verbose_name': 'Fichier de déclaration de changement',
                'verbose_name_plural': 'Fichiers de déclaration de changement',
                'ordering': ['provider_date_of_sending'],
            },
        ),
        migrations.CreateModel(
            name='DeclarationDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_count', models.IntegerField(verbose_name='Year of count')),
                ('month_of_count', models.IntegerField(verbose_name='Month of count')),
                ('change_type', models.CharField(choices=[('ENTRY', 'Entry'), ('EXIT', 'Exit'), ('CORRECTION', 'Correction')], max_length=10, verbose_name='Change type')),
                ('change_reference', models.CharField(help_text='Le prestataire est libre de choisir son système de référencement des déclarations', max_length=50, verbose_name='Change reference')),
                ('change_organism_identifier', models.CharField(blank=True, help_text='Correspond à la référence donnée à la déclaration par l’organisme gestionnaire. Celui-ci sera renseigné dans le fichier retour. Ce champ doit obligatoirement être renseigné lors d’une déclaration de correction.', max_length=50, null=True, verbose_name='Change organism identifier')),
                ('change_date', models.DateField(default=django.utils.timezone.now, help_text='Date d’entrée ou de sortie indiquant le jour, le mois et l’année.', verbose_name='Change date')),
                ('information', models.TextField(help_text='Ce champ est optionnel et peut contenir du texte libre.', max_length=50, verbose_name='Information')),
                ('link_to_chg_dec_file', models.ForeignKey(help_text='Link to the file containing the declaration of change', on_delete=django.db.models.deletion.CASCADE, related_name='longtermcaredeclaration_to_chg_dec_file', to='dependence.changedeclarationfile')),
                ('patient', models.ForeignKey(help_text='Only looks for patients covered by long-term care insurance, check that the checkbox is validated if you cannot find your patient', limit_choices_to={'is_under_dependence_insurance': True}, on_delete=django.db.models.deletion.CASCADE, related_name='longtermcare_to_patient', to='invoices.patient')),
            ],
        ),
    ]
