# Generated by Django 4.1.7 on 2023-03-02 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependence', '0038_new_way_of_sending_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='changedeclarationfile',
            name='internal_reference',
            field=models.CharField(default=0, max_length=10, verbose_name='Internal reference'),
            preserve_default=False,
        ),
    ]
