# Generated by Django 4.1.7 on 2023-03-03 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependence', '0040_add_boolean_trigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changedeclarationfile',
            name='force_xml_generation',
            field=models.BooleanField(default=False, help_text="Force the generation of the XML file, don't forget to check the checkbox before saving the form", verbose_name='Force XML generation'),
        ),
    ]
