# Generated by Django 4.1.7 on 2023-03-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependence', '0041_add_boolean_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='changedeclarationfile',
            name='send_status_to_ftp_server',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Send status to FTP server'),
        ),
        migrations.AddField(
            model_name='changedeclarationfile',
            name='sent_to_ftp_server',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Sent to FTP server'),
        ),
    ]
