# Generated by Django 4.1.7 on 2023-03-04 13:53

import dependence.medicalcaresummary
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependence', '0042_fix_fox'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalCareSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('parsing_date', models.DateTimeField(verbose_name='Date de parsing')),
                ('force_update', models.BooleanField(default=False, verbose_name='Forcer la mise à jour')),
                ('generated_return_xml', models.FileField(blank=True, null=True, upload_to=dependence.medicalcaresummary.file_path_for_spc, verbose_name='Fichier CNS SPC')),
                ('count_of_supported_persons', models.IntegerField(blank=True, null=True, verbose_name='Nombre de personnes prises en charge')),
                ('date_of_submission', models.DateField(blank=True, null=True, verbose_name="Date d'envoi du fichier")),
            ],
        ),
    ]
