# Generated by Django 4.1.7 on 2023-03-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependence', '0043_spc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalcaresummary',
            name='parsing_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de parsing'),
        ),
    ]
