# Generated by Django 4.1.7 on 2023-03-04 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0151_some_cleanup_and_tech_fields'),
        ('dependence', '0044_spc'),
    ]

    operations = [
        migrations.CreateModel(
            name='LongTermCareItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalCareSummaryPerPatient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('date_of_request', models.DateField(verbose_name='Date de demande')),
                ('referent', models.CharField(max_length=50, verbose_name='Référent')),
                ('date_of_evaluation', models.DateField(verbose_name="Date d'évaluation")),
                ('date_of_notification', models.DateField(verbose_name='Date de notification')),
                ('plan_number', models.CharField(max_length=25, verbose_name='Numéro de plan')),
                ('decision_number', models.CharField(max_length=25, verbose_name='Numéro de décision')),
                ('level_of_needs', models.IntegerField(verbose_name='Niveau de besoins')),
                ('start_of_support', models.DateField(verbose_name='Début de prise en charge')),
                ('end_of_support', models.DateField(blank=True, null=True, verbose_name='Fin de prise en charge')),
                ('date_of_decision', models.DateField(verbose_name='Date de décision')),
                ('special_package', models.CharField(blank=True, max_length=10, null=True, verbose_name='Forfait spécial')),
                ('nature_package', models.IntegerField(blank=True, null=True, verbose_name='Forfait Prestation en nature')),
                ('cash_package', models.IntegerField(blank=True, null=True, verbose_name='Forfait Prestation en espèces')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_care_summary_per_patient', to='invoices.patient')),
            ],
        ),
        migrations.CreateModel(
            name='SharedMedicalCareSummaryPerPatientDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn_code', models.CharField(max_length=13, verbose_name='SN Code')),
                ('number_of_care', models.IntegerField(verbose_name='Fréquence')),
                ('periodicity', models.CharField(choices=[('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly'), ('A', 'Annually')], max_length=15, verbose_name='Périodicité')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_medical_care_summary_per_patient_detail_item', to='dependence.longtermcareitem')),
                ('medical_care_summary_per_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_medical_care_summary_per_patient_detail', to='dependence.medicalcaresummaryperpatient')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalCareSummaryPerPatientDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_care', models.IntegerField(verbose_name='Fréquence')),
                ('periodicity', models.CharField(choices=[('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly'), ('A', 'Annually')], max_length=15, verbose_name='Périodicité')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_care_summary_per_patient_detail_item', to='dependence.longtermcareitem')),
                ('medical_care_summary_per_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_care_summary_per_patient_detail', to='dependence.medicalcaresummaryperpatient')),
            ],
        ),
    ]
