# Generated by Django 4.1.7 on 2023-03-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependence', '0045_spc'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalcaresummaryperpatient',
            name='fmi_right',
            field=models.BooleanField(default=False, verbose_name='Droit FMI'),
        ),
    ]
