# Generated by Django 4.1.7 on 2023-03-04 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0151_some_cleanup_and_tech_fields'),
        ('dependence', '0048_spc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='longtermcareitem',
            options={'ordering': ['code']},
        ),
        migrations.AlterUniqueTogether(
            name='medicalcaresummaryperpatient',
            unique_together={('patient', 'plan_number', 'decision_number', 'date_of_decision')},
        ),
    ]
