# Generated by Django 4.1.7 on 2023-03-04 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependence', '0049_spc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharedmedicalcaresummaryperpatientdetail',
            name='sn_code',
        ),
        migrations.AddField(
            model_name='medicalcaresummaryperpatient',
            name='sn_code_aidant',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='SN Code Aidant'),
        ),
    ]
