# Generated by Django 4.1.7 on 2023-03-04 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dependence', '0050_spc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='longtermcareitem',
            options={'ordering': ['code'], 'verbose_name': "Acte d'assurance dépendance", 'verbose_name_plural': "Actes d'assurance dépendance"},
        ),
        migrations.AlterModelOptions(
            name='medicalcaresummary',
            options={'verbose_name': 'Synthèse de prise en charge de la CNS', 'verbose_name_plural': 'Synthèses de prise en charge de la CNS'},
        ),
        migrations.AlterModelOptions(
            name='medicalcaresummaryperpatient',
            options={'verbose_name': 'Synthèse de prise en charge par patient', 'verbose_name_plural': 'Synthèses de prise en charge par patient'},
        ),
        migrations.AlterModelOptions(
            name='medicalcaresummaryperpatientdetail',
            options={'verbose_name': 'Prestation Prestataire', 'verbose_name_plural': 'Prestations Prestataire'},
        ),
        migrations.AlterModelOptions(
            name='sharedmedicalcaresummaryperpatientdetail',
            options={'verbose_name': 'Prestation Aidant', 'verbose_name_plural': 'Prestations Aidant'},
        ),
    ]
