# Generated by Django 4.1.7 on 2023-03-05 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0151_some_cleanup_and_tech_fields'),
        ('dependence', '0051_spc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='declarationdetail',
            options={'verbose_name': 'Déclarations assurance dépendance', 'verbose_name_plural': 'Déclarations assurance dépendance'},
        ),
        migrations.AlterUniqueTogether(
            name='declarationdetail',
            unique_together={('patient', 'change_reference')},
        ),
    ]
