# Generated by Django 4.1.7 on 2023-03-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependence', '0052_spc'),
    ]

    operations = [
        migrations.AddField(
            model_name='changedeclarationfile',
            name='updates_log',
            field=models.TextField(blank=True, null=True, verbose_name='Updates log'),
        ),
    ]
