# Generated by Django 4.1.7 on 2023-03-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependence', '0053_spc'),
    ]

    operations = [
        migrations.AddField(
            model_name='declarationdetail',
            name='change_anomaly',
            field=models.TextField(blank=True, help_text='Ce champ est optionnel et peut contenir du texte libre.', max_length=80, null=True, verbose_name='Change anomaly'),
        ),
    ]
