# Generated by Django 4.1.7 on 2023-03-12 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependence', '0054_spc'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientanamnesis',
            name='birth_place',
            field=models.CharField(blank=True, default=None, help_text='Ville/Pays', max_length=50, null=True, verbose_name='Lieu de naissance'),
        ),
        migrations.AddField(
            model_name='patientanamnesis',
            name='contract_end_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Date de fin du contrat'),
        ),
        migrations.AddField(
            model_name='patientanamnesis',
            name='contract_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='contracts/', verbose_name='Contrat'),
        ),
        migrations.AddField(
            model_name='patientanamnesis',
            name='contract_signed_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Date de signature du contrat'),
        ),
        migrations.AddField(
            model_name='patientanamnesis',
            name='contract_start_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Date de début du contrat'),
        ),
    ]
