# Generated by Django 4.1.7 on 2023-03-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependence', '0055_enrich_anamnesis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientanamnesis',
            name='treatments',
            field=models.TextField(blank=True, default=None, max_length=1000, null=True, verbose_name='Traitements'),
        ),
    ]
