# Generated by Django 4.1.7 on 2023-03-22 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0160_new_field_on_patient'),
        ('dependence', '0056_enlarge_anamnesis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyparameters',
            name='patient',
            field=models.ForeignKey(limit_choices_to=models.Q(('is_under_dependence_insurance', True), ('is_eligible_to_parameter_surveillance', True), _connector='OR'), on_delete=django.db.models.deletion.PROTECT, related_name='health_params_to_patient', to='invoices.patient'),
        ),
    ]
