# Generated by Django 4.1.7 on 2023-03-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependence', '0057_new_field_on_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='careplandetail',
            name='long_term_care_items',
            field=models.ManyToManyField(blank=True, related_name='care_plan_detail_to_long_term_care_item', to='dependence.longtermcareitem', verbose_name='Prestations Assurance dépendance'),
        ),
    ]
