# Generated by Django 4.1.7 on 2023-03-22 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dependence', '0058_associate_careitems_to_careplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careplandetail',
            name='required_technical_resources',
        ),
    ]
