# Generated by Django 4.1.7 on 2023-03-23 15:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dependence', '0061_associate_careitems_to_events'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='careoccurrence',
            options={'ordering': ['value'], 'verbose_name': 'Occurence des soins', 'verbose_name_plural': 'Occurences'},
        ),
        migrations.AddField(
            model_name='medicalcaresummaryperpatient',
            name='date_of_notification_to_provider',
            field=models.DateField(default=django.utils.timezone.now, verbose_name="Date d'envoi au prestataire"),
            preserve_default=False,
        ),
    ]
