# Generated by Django 4.1.7 on 2023-03-25 14:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0162_associate_careitems_to_events'),
        ('dependence', '0062_date_envoi_prestataire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careplandetail',
            name='req_skills',
        ),
        migrations.AddField(
            model_name='careplanmaster',
            name='medical_care_summary_per_patient',
            field=models.ForeignKey(blank=True, help_text='Lien vers Résumé des soins médicaux par patient reçu de la CNS', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='care_plan_to_medical_care_summary_per_patient', to='dependence.medicalcaresummaryperpatient'),
        ),
        migrations.CreateModel(
            name='LongTermCareInvoiceFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Year')),
                ('month', models.PositiveIntegerField(verbose_name='Month')),
                ('invoice_sent_date', models.DateField(default=django.utils.timezone.now, verbose_name='Invoice Sent Date')),
                ('generated_invoice_file', models.FileField(upload_to='', verbose_name='Generated Invoice File')),
                ('force_regeneration', models.BooleanField(default=False, verbose_name='Force Regeneration')),
                ('generation_report', models.TextField(verbose_name='Generation Report')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='invoices.patient')),
            ],
            options={
                'verbose_name': 'Facture assurance dépendance',
                'verbose_name_plural': 'Factures assurance dépendance',
                'unique_together': {('year', 'month')},
            },
        ),
    ]
