# Generated by Django 4.1.7 on 2023-03-28 17:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0162_associate_careitems_to_events'),
        ('dependence', '0063_link_plan_to_plan_provided_tocns'),
    ]

    operations = [
        migrations.AddField(
            model_name='longtermcareinvoicefile',
            name='invoice_end_period',
            field=models.DateField(default=datetime.datetime(2023, 3, 28, 17, 5, 21, 365533, tzinfo=datetime.timezone.utc), verbose_name='Invoice End Period'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='longtermcareinvoicefile',
            name='invoice_start_period',
            field=models.DateField(default=datetime.datetime(2023, 3, 28, 17, 5, 24, 578016, tzinfo=datetime.timezone.utc), verbose_name='Invoice Start Period'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='LongTermCareInvoiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_date', models.DateField(verbose_name='Item Date')),
                ('status', models.CharField(choices=[('DONE', 'Done'), ('NOT_DONE', 'Not Done'), ('CANCELLED', 'Cancelled')], default='DONE', max_length=1, verbose_name='Status')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('assigned_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_employee', to='invoices.employee')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='dependence.longtermcareinvoicefile')),
                ('long_term_care_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='long_term_care_item', to='dependence.longtermcareitem')),
            ],
            options={
                'verbose_name': 'Ligne de facture assurance dépendance',
                'verbose_name_plural': 'Lignes de facture assurance dépendance',
            },
        ),
    ]
