# Generated by Django 4.1.7 on 2023-03-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependence', '0064_aec_invoicing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='longtermcareinvoicefile',
            name='generated_invoice_file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Generated Invoice File'),
        ),
        migrations.AlterField(
            model_name='longtermcareinvoicefile',
            name='generation_report',
            field=models.TextField(blank=True, null=True, verbose_name='Generation Report'),
        ),
        migrations.AlterField(
            model_name='longtermcareinvoiceitem',
            name='status',
            field=models.CharField(choices=[('DONE', 'Done'), ('NOT_DONE', 'Not Done'), ('CANCELLED', 'Cancelled')], default='DONE', max_length=100, verbose_name='Status'),
        ),
    ]
