# Generated by Django 4.1.7 on 2023-03-30 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dependence', '0065_aec_invoicing'),
    ]

    operations = [
        migrations.CreateModel(
            name='LongTermCareMonthlyStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Year')),
                ('month', models.PositiveIntegerField(verbose_name='Month')),
                ('generated_invoice_file', models.FileField(blank=True, null=True, upload_to='', verbose_name='Generated Invoice File')),
                ('force_regeneration', models.BooleanField(default=False, verbose_name='Force Regeneration')),
                ('date_of_submission', models.DateField(blank=True, null=True, verbose_name="Date d'envoi du fichier")),
                ('generated_invoice_file_response', models.FileField(blank=True, null=True, upload_to='', verbose_name='Generated Invoice Response File')),
                ('date_of_receipt', models.DateField(blank=True, null=True, verbose_name='Date de réception du fichier')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
            ],
            options={
                'verbose_name': 'Décompte mensuel de factures',
                'verbose_name_plural': 'Décomptes mensuels de factures',
            },
        ),
        migrations.AlterUniqueTogether(
            name='longtermcareinvoicefile',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='longtermcareinvoicefile',
            name='force_regeneration',
        ),
        migrations.RemoveField(
            model_name='longtermcareinvoicefile',
            name='generated_invoice_file',
        ),
        migrations.RemoveField(
            model_name='longtermcareinvoicefile',
            name='generation_report',
        ),
        migrations.RemoveField(
            model_name='longtermcareinvoicefile',
            name='invoice_sent_date',
        ),
        migrations.RemoveField(
            model_name='longtermcareinvoicefile',
            name='month',
        ),
        migrations.RemoveField(
            model_name='longtermcareinvoicefile',
            name='year',
        ),
        migrations.AddField(
            model_name='longtermcareinvoicefile',
            name='link_to_monthly_statement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_statement', to='dependence.longtermcaremonthlystatement'),
        ),
    ]
