# Generated by Django 4.1.8 on 2023-04-26 16:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0164_add_more_decimals_to_care_code'),
        ('dependence', '0066_aec_invoicing'),
    ]

    operations = [
        migrations.CreateModel(
            name='LongTermPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(max_length=50)),
                ('package', models.BooleanField(default=False, verbose_name='Forfait')),
                ('dependence_level', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)])),
                ('weekly_package', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Acte assurance dépendance',
                'verbose_name_plural': 'Acte assurance dépendance',
                'ordering': ['code'],
            },
        ),
        migrations.RenameModel(
            old_name='LongTermCareInvoiceItem',
            new_name='LongTermCareActivity',
        ),
        migrations.AlterModelOptions(
            name='longtermcareactivity',
            options={'verbose_name': "Ligne d'activité assurance dépendance", 'verbose_name_plural': "Lignes d'activités assurance dépendance"},
        ),
        migrations.AddField(
            model_name='longtermcareitem',
            name='short_description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='longtermcareitem',
            name='weekly_package',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='medicalcaresummaryperpatient',
            name='date_of_change_to_new_plan',
            field=models.DateField(blank=True, null=True, verbose_name='Date de changement vers un nouveau plan'),
        ),
        migrations.AlterField(
            model_name='longtermcareinvoicefile',
            name='patient',
            field=models.ForeignKey(limit_choices_to=models.Q(('is_under_dependence_insurance', True)), on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='invoices.patient'),
        ),
        migrations.AlterField(
            model_name='monthlyparameters',
            name='params_month',
            field=models.IntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], default=4),
        ),
        migrations.CreateModel(
            name='LongTermPackagePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_validity_package', to='dependence.longtermpackage')),
            ],
            options={
                'verbose_name': 'Prix assurance dépendance',
                'verbose_name_plural': 'Prix assurance dépendance',
                'ordering': ['package'],
            },
        ),
        migrations.CreateModel(
            name='LongTermCareInvoiceLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_period', models.DateField(verbose_name='Date Début période')),
                ('end_period', models.DateField(blank=True, null=True, verbose_name='Date Fin période')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_line', to='dependence.longtermcareinvoicefile')),
                ('long_term_care_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='long_term_care_package', to='dependence.longtermpackage')),
            ],
            options={
                'verbose_name': 'Ligne de facture assurance dépendance',
                'verbose_name_plural': 'Lignes de facture assurance dépendance',
            },
        ),
    ]
