# Generated by Django 4.1.8 on 2023-05-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependence', '0069_additional_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='longtermcareitem',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
