# Generated by Django 4.1.8 on 2023-05-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependence', '0070_descripton_no_more_required'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='longtermcareitem',
            options={'ordering': ['code'], 'verbose_name': 'Relevé type des aides et soins', 'verbose_name_plural': 'Relevés type des aides et soins'},
        ),
        migrations.AlterField(
            model_name='longtermcareitem',
            name='short_description',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
