# Generated by Django 4.1.8 on 2023-05-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependence', '0071_short_desc_a_bit_larger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='longtermcareitem',
            name='short_description',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
