# Generated by Django 4.1.8 on 2023-05-03 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0169_additional_phone_number'),
        ('dependence', '0072_short_desc_a_bit_larger'),
    ]

    operations = [
        migrations.CreateModel(
            name='LongTermMonthlyActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Year')),
                ('month', models.PositiveIntegerField(verbose_name='Month')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='longtermmonthlyactivity_patient', to='invoices.patient')),
            ],
            options={
                'verbose_name': "Relevé d'activité mensuel",
                'verbose_name_plural': "Relevés d'activité mensuels",
                'unique_together': {('year', 'month', 'patient')},
            },
        ),
        migrations.CreateModel(
            name='LongTermMonthlyActivityDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_date', models.DateField(verbose_name='Activity Date')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_dtl_to_item', to='dependence.longtermcareitem')),
                ('long_term_monthly_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_dtl_to_monthly_activity', to='dependence.longtermmonthlyactivity')),
            ],
            options={
                'verbose_name': "Détail du relevé d'activité mensuel",
                'verbose_name_plural': "Détails des relevés d'activité mensuels",
            },
        ),
    ]
