# Generated by Django 4.1.8 on 2023-05-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependence', '0073_new_long_term_activity_object'),
    ]

    operations = [
        migrations.CreateModel(
            name='LongTermMonthlyActivityFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Year')),
                ('month', models.PositiveIntegerField(verbose_name='Month')),
                ('provider_date_of_sending', models.DateField(verbose_name='Provider Date of Sending')),
                ('file', models.FileField(upload_to='longtermmonthlyactivityfiles/')),
                ('version_number', models.PositiveIntegerField(verbose_name='Version Number')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('monthly_activities', models.ManyToManyField(to='dependence.longtermmonthlyactivity', verbose_name='Activities')),
            ],
            options={
                'verbose_name': "Fichier d'activité mensuel",
                'verbose_name_plural': "Fichiers d'activité mensuels",
            },
        ),
    ]
