# Generated by Django 4.1.8 on 2023-05-08 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dependence', '0076_create_monthly_activity_file_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='longtermmonthlyactivitydetail',
            name='long_term_monthly_activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_details', to='dependence.longtermmonthlyactivity'),
        ),
    ]
