# Generated by Django 4.1.8 on 2023-05-09 10:57

import dependence.activity
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependence', '0077_create_monthly_activity_file_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='longtermmonthlyactivityfile',
            name='force_creation',
            field=models.BooleanField(default=False, verbose_name='Force Creation'),
        ),
        migrations.AlterField(
            model_name='longtermmonthlyactivityfile',
            name='file',
            field=models.FileField(upload_to=dependence.activity.long_term_care_activity_declaration_file_path, verbose_name='File'),
        ),
    ]
