# Generated by Django 4.1.8 on 2023-05-09 11:24

import dependence.activity
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependence', '0078_file_force_creation_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='longtermmonthlyactivityfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=dependence.activity.long_term_care_activity_declaration_file_path, verbose_name='File'),
        ),
    ]
