# Generated by Django 4.1.9 on 2023-05-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependence', '0079_file_force_creation_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='longtermmonthlyactivityfile',
            name='monthly_activities',
            field=models.ManyToManyField(blank=True, help_text='Please first save year and month to be able to add activities', to='dependence.longtermmonthlyactivity', verbose_name='Activities'),
        ),
    ]
