# Generated by Django 4.1.9 on 2023-05-16 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dependence', '0083_invoice_dtl_moved_as_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='longtermcareinvoiceline',
            options={'verbose_name': 'Forfait de facture assurance dépendance', 'verbose_name_plural': 'Forfaits de facture assurance dépendance'},
        ),
        migrations.RemoveField(
            model_name='longtermcareinvoiceline',
            name='long_term_care_package',
        ),
        migrations.AddField(
            model_name='longtermcareinvoiceline',
            name='long_care_item_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_line_to_long_term_care_item', to='dependence.longtermcareitem'),
        ),
    ]
