# Generated by Django 4.1.9 on 2023-05-16 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0169_additional_phone_number'),
        ('dependence', '0084_invoice_dtl_moved_as_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='LongTermCareActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_date', models.DateField(verbose_name='Item Date')),
                ('status', models.CharField(choices=[('DONE', 'Done'), ('NOT_DONE', 'Not Done'), ('CANCELLED', 'Cancelled')], default='DONE', max_length=100, verbose_name='Status')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('assigned_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_employee', to='invoices.employee')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='dependence.longtermcareinvoicefile')),
                ('long_term_care_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='long_term_care_item', to='dependence.longtermcareitem')),
            ],
            options={
                'verbose_name': "Ligne d'activité assurance dépendance",
                'verbose_name_plural': "Lignes d'activités assurance dépendance",
            },
        ),
        migrations.AlterModelOptions(
            name='longtermcareinvoiceline',
            options={'verbose_name': 'Ligne de facture assurance dépendance', 'verbose_name_plural': 'Lignes de facture assurance dépendance'},
        ),
        migrations.RemoveField(
            model_name='longtermcareinvoiceline',
            name='long_care_item_link',
        ),
        migrations.AddField(
            model_name='longtermcareinvoiceline',
            name='long_term_care_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='long_term_care_package', to='dependence.longtermpackage'),
        ),
        migrations.DeleteModel(
            name='LongTermCareInvoiceItem',
        ),
    ]
