# Generated by Django 4.1.9 on 2023-05-16 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dependence', '0085_invoice_dtl_moved_as_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='LongTermCareInvoiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('care_date', models.DateField(verbose_name='Date Début période')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_item', to='dependence.longtermcareinvoicefile')),
                ('long_term_care_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_item_to_long_term_care_package', to='dependence.longtermpackage')),
            ],
            options={
                'verbose_name': 'Item facture assurance dépendance',
                'verbose_name_plural': 'Item de facture assurance dépendance',
            },
        ),
    ]
