# Generated by Django 4.1.9 on 2023-05-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependence', '0086_invoice_dtl_moved_as_item'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='longtermpackageprice',
            constraint=models.UniqueConstraint(fields=('package', 'start_date'), name='unique package price'),
        ),
    ]
