# Generated by Django 4.1.9 on 2023-05-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependence', '0087_add_unique_constraint_on_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalcaresummaryperpatient',
            name='date_of_start_of_plan_for_us',
            field=models.DateField(blank=True, null=True, verbose_name='Date début application du plan'),
        ),
        migrations.AlterField(
            model_name='medicalcaresummaryperpatient',
            name='date_of_change_to_new_plan',
            field=models.DateField(blank=True, help_text="Date fin d'application du plan", null=True, verbose_name='Date de changement vers un nouveau plan'),
        ),
    ]
