# Generated by Django 4.1.9 on 2023-05-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependence', '0088_add_new_field_to_calculate_latest_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='longtermcareinvoiceitem',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Quantité'),
        ),
    ]
