# Generated by Django 4.1.9 on 2023-05-23 12:40

import dependence.invoicing
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependence', '0089_add_qty_item_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='longtermcaremonthlystatement',
            name='generated_invoice_file',
            field=models.FileField(blank=True, null=True, upload_to=dependence.invoicing.long_term_care_monthly_statement_file_path, verbose_name='Generated Invoice File'),
        ),
    ]
