# Generated by Django 4.1.10 on 2023-07-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependence', '0092_alternate_addr'),
    ]

    operations = [
        migrations.AddField(
            model_name='changedeclarationfile',
            name='force_xml_return_check',
            field=models.BooleanField(default=False, help_text="Force the analysis of the XML Retour file, don't forget to check the checkbox before saving the form", verbose_name='Force XML Retour Check'),
        ),
    ]
