# Generated by Django 4.1.10 on 2023-08-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependence', '0093_force_return_check'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='longtermmonthlyactivitydetail',
            options={'ordering': ['activity_date'], 'verbose_name': "Détail du relevé d'activité mensuel", 'verbose_name_plural': "Détails des relevés d'activité mensuels"},
        ),
        migrations.AlterField(
            model_name='monthlyparameters',
            name='params_month',
            field=models.IntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], default=8),
        ),
    ]
