# Generated by Django 4.1.11 on 2023-09-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependence', '0094_google_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyparameters',
            name='params_month',
            field=models.IntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], default=9),
        ),
    ]
