# Generated by Django 4.1.11 on 2023-09-25 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0186_remove_contact_p_a_physician'),
        ('dependence', '0095_cleanup_regulier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedphysician',
            name='assigned_physician',
            field=models.ForeignKey(blank=True, default=None, help_text='Please enter physician of the patient', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dep_assigned_physicians', to='invoices.physician', verbose_name='Médecin'),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='patient_anamnesis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dep_contactpers_to_anamnesis', to='dependence.patientanamnesis'),
        ),
    ]
