# Generated by Django 4.2.6 on 2023-10-06 10:05

import django.core.validators
from django.db import migrations, models

import dependence.invoicing


class Migration(migrations.Migration):

    def update_stools_parameter(apps, schema_editor):
        # Get the model from the versioned app registry
        YourModel = apps.get_model('dependence', 'tensionandtemperatureparameters')

        # Iterate through all instances of the model
        for instance in YourModel.objects.all():
            # Update stools_parameter based on stools
            instance.stools_parameter = instance.stools != 0
            instance.save(update_fields=['stools_parameter'])

    dependencies = [
        ('dependence', '0098_remove_link_to_detail_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='tensionandtemperatureparameters',
            name='stools_parameter',
            field=models.BooleanField(default=False, verbose_name='Selles'),
        ),
        migrations.AlterField(
            model_name='longtermcaremonthlystatement',
            name='generated_invoice_file_response',
            field=models.FileField(blank=True, null=True, upload_to=dependence.invoicing.long_term_care_monthly_statement_response_file_path, verbose_name='Generated Invoice Response File'),
        ),
        migrations.AlterField(
            model_name='longtermpackage',
            name='dependence_level',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(780)]),
        ),
        migrations.RunPython(update_stools_parameter),

    ]
