# Generated by Django 4.2.6 on 2023-10-11 09:48

import dependence.invoicing
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dependence', '0100_stools_param'),
    ]

    operations = [
        migrations.AddField(
            model_name='longtermcareinvoiceitem',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Paid'),
        ),
        migrations.AddField(
            model_name='longtermcareinvoiceline',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Paid'),
        ),
        migrations.CreateModel(
            name='LongTermCareMonthlyStatementSending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xml_invoice_file', models.FileField(blank=True, null=True, upload_to=dependence.invoicing.long_term_care_monthly_statement_file_path_bis, verbose_name='Generated Invoice File')),
                ('received_invoice_file_response', models.FileField(blank=True, null=True, upload_to=dependence.invoicing.long_term_care_monthly_statement_response_file_path_bis, verbose_name='Received Invoice Response File')),
                ('scan_of_signed_invoice', models.FileField(blank=True, null=True, upload_to='long_term_invoices/signed/', verbose_name='Scan of Signed Invoice')),
                ('date_of_receipt_of_response_file', models.DateField(blank=True, null=True, verbose_name='Date de réception du fichier de retour')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('link_to_monthly_statement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_statement_xml_file', to='dependence.longtermcaremonthlystatement')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_message', models.TextField()),
                ('error_message_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dependence.longtermcareinvoicefile')),
                ('statement_sending', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dependence.longtermcaremonthlystatementsending')),
            ],
        ),
    ]
