# Generated by Django 4.2.6 on 2023-10-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependence', '0101_multiple_xml_invoices_and_responses_should_be_possible'),
    ]

    operations = [
        migrations.AddField(
            model_name='longtermcaremonthlystatementsending',
            name='date_of_sending_xml_file',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'envoi du fichier"),
        ),
    ]
