# Generated by Django 4.2.6 on 2023-10-31 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependence', '0102_sending_date_per_generated_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='longtermcareactivity',
            options={'ordering': ['item_date'], 'verbose_name': "Ligne d'activité assurance dépendance", 'verbose_name_plural': "Lignes d'activités assurance dépendance"},
        ),
        migrations.AlterField(
            model_name='longtermmonthlyactivitydetail',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Quantity'),
        ),
    ]
