# Generated by Django 4.2.6 on 2023-11-08 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dependence', '0103_activity_details_qty_in_decimals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyparameters',
            name='params_month',
            field=models.IntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], default=11),
        ),
        migrations.CreateModel(
            name='FallDeclarationReportPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='', help_text='Please, give a description of the uploaded image.', max_length=250, null=True, verbose_name='Description')),
                ('image', models.ImageField(help_text='Please, upload a picture.', upload_to='fall_declaration_report_pictures/', verbose_name='Image')),
                ('fall', models.ForeignKey(help_text='Here, you can upload pictures if needed', on_delete=django.db.models.deletion.CASCADE, related_name='fall_declaration_report_pictures', to='dependence.falldeclaration')),
            ],
            options={
                'verbose_name': 'Image attachée au rapport',
                'verbose_name_plural': 'Images attachées au rapport',
            },
        ),
    ]
